In [61]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
import numpy as np
from datetime import datetime
from itertools import product
import json
import multiprocessing

# this is just a file with a worker function for multiprocessing
# (otherwise multiprocessing doesn't work in Jupyter on Windows)
import worker

In [192]:
# brand names have been coppied from auto.ru manually and stored in brands.xlsx
df_brands = pd.read_excel('brands.xlsx')
df_brands

         Brands  Count
0            AC      2
1           AMC      2
2         Acura     46
3    Alfa Romeo     27
4        Alpina      2
..          ...    ...
120        ЛуАЗ     11
121     Москвич    101
122         СМЗ      1
123       ТагАЗ     34
124         УАЗ    450

[125 rows x 2 columns]

In [193]:
# let's remove rare (<400) and Russian/Soviet brands
df_brands = df_brands[(df_brands['Count'] > 400) & ~(df_brands['Brands'].isin(['LADA (ВАЗ)', 'ГАЗ', 'УАЗ']))]

In [194]:
df_brands

            Brands  Count
8             Audi   2750
9              BMW   5283
19       Chevrolet   1352
21         Citroen    692
39            Ford   2017
51           Honda    574
53         Hyundai   3470
54        Infiniti    599
59            Jeep    401
60             Kia   3850
64      Land Rover   1192
65           Lexus    699
70            MINI    494
73           Mazda   1333
75   Mercedes-Benz   8770
78      Mitsubishi   2449
80          Nissan   3855
82            Opel   1411
85         Peugeot    754
88         Porsche    596
92         Renault   2790
99           Skoda   2378
102         Subaru    484
103         Suzuki    830
105         Toyota   2465
107     Volkswagen   4621
108          Volvo   1285

In [244]:
def crawl_auto(brands_lst, year_from=1980, year_to=2021, fr=1, to=10000000, radius=200):
    """
    This function crawls auto.ru. Idea for this function was 
    taken from https://github.com/DarkLabel1/YouTube/blob/master/Auto_ru.py
    
    After that it was slightly modified to fit the requirements of kaggle competition
    
    Arguments:
        brands - a list of brands to process
        year_from and year_to - range of car production years
        fr and to - used for testing (you can slice year_brand list to make the output longer or shorter
        if you need to test something)
        radius - radius from Moscow
    """
    # capitalize brand names
    brands = brands_lst.copy()
    brands = [b.upper() for b in brands]
    
    # all the years to consider
    year_range = list(np.arange(year_from, year_to))
    
    # pairs of year and brand to iterate over them
    year_brand = list(product(year_range, brands))
    
    # these 2 won't change
    URL = 'https://auto.ru/-/ajax/desktop/listing/' #URL for the post request

    # header for the post request
    HEADERS = {
        'Accept': '*/*',
        'Accept-Encoding': 'gzip, deflate, br',
        'Accept-Language': 'ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3',
        'Connection': 'keep-alive',
        'Content-Length': '137',
        'content-type': 'application/json',
        'Cookie': 'autoru_gdpr=1; _csrf_token=1c0ed592ec162073ac34d79ce511f0e50d195f763abd8c24; autoru_sid=a%3Ag5e3b198b299o5jhpv6nlk0ro4daqbpf.fa3630dbc880ea80147c661111fb3270%7C1580931467355.604800.8HnYnADZ6dSuzP1gctE0Fw.cd59AHgDSjoJxSYHCHfDUoj-f2orbR5pKj6U0ddu1G4; autoruuid=g5e3b198b299o5jhpv6nlk0ro4daqbpf.fa3630dbc880ea80147c661111fb3270; suid=48a075680eac323f3f9ad5304157467a.bc50c5bde34519f174ccdba0bd791787; from_lifetime=1580933172327; from=yandex; X-Vertis-DC=myt; crookie=bp+bI7U7P7sm6q0mpUwAgWZrbzx3jePMKp8OPHqMwu9FdPseXCTs3bUqyAjp1fRRTDJ9Z5RZEdQLKToDLIpc7dWxb90=; cmtchd=MTU4MDkzMTQ3MjU0NQ==; yandexuid=1758388111580931457; bltsr=1; navigation_promo_seen-recalls=true',
        'Host': 'auto.ru',
        'origin': 'https://auto.ru',
        'Referer': 'https://auto.ru/ryazan/cars/mercedes/all/',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0',
        'x-client-app-version': '202002.03.092255',
        'x-client-date': '1580933207763',
        'x-csrf-token': '1c0ed592ec162073ac34d79ce511f0e50d195f763abd8c24',
        'x-page-request-id': '60142cd4f0c0edf51f96fd0134c6f02a',
        'x-requested-with': 'fetch'
    }    
    
    result = []
    
    for yb in year_brand[fr:to]:  
        i = 1 # initializing i for pagination 
        l = 1 # initializing l that will be replaced by len(data) below
        while l > 0:
            # Post request parameters are changed within the loop
            PARAMS = {
                 'catalog_filter' : [{"mark": yb[1]}],
                 'section': "all",
                 'category': "cars",
                 'sort': "fresh_relevance_1-desc",
                 'page': i,
                 'geo_radius' : str(radius),
                 'year_from' : str(yb[0]),
                 'year_to' : str(yb[0]),
                 'geo_id' : [213]
                }

            i+=1
            
            response = requests.post(URL, json=PARAMS, headers=HEADERS) 
            try:
                data = response.json()['offers']
            except: 
                print(f'Failed for {yb[1]}, year {yb[0]} page {i} - let us go on!')
                
            l = len(data)
            if l > 0:
                print(f'{yb[1]}, year {yb[0]} : {l} entries')
                for o in data:
                    result.append(o)
    
    print('Crawling done!!!')
    return result;

In [245]:
def save_to_file(j):
    """
    Saves a json string to a file
    """
    jsonString = json.dumps(j, indent=4)
    with open("data.json", "w") as f:
        f.write(jsonString)

In [246]:
j = crawl_auto(brands_lst=list(df_brands['Brands']), year_from=1970, year_to=2022)

# I didn't have time to complete the parser in one go. That's why I decided to save the results to JSON and process
# this file later. The file for Moscow (+200 KM radius) and all the main brands starting from 1970 takes about 1.9 GB. Please
# take that into account if you decide to use the same approach.
save_to_file(j)

CHEVROLET, year 1970 : 2 entries
FORD, year 1970 : 1 entries
CHEVROLET, year 1971 : 1 entries
SKODA, year 1971 : 1 entries
BMW, year 1972 : 1 entries
CHEVROLET, year 1972 : 1 entries
OPEL, year 1972 : 2 entries
VOLKSWAGEN, year 1972 : 1 entries
VOLKSWAGEN, year 1973 : 1 entries
CHEVROLET, year 1974 : 1 entries
CITROEN, year 1974 : 1 entries
FORD, year 1974 : 1 entries
CHEVROLET, year 1976 : 1 entries
FORD, year 1978 : 1 entries
OPEL, year 1978 : 1 entries
RENAULT, year 1978 : 1 entries
VOLKSWAGEN, year 1978 : 1 entries
VOLVO, year 1978 : 1 entries
CHEVROLET, year 1979 : 3 entries
NISSAN, year 1979 : 1 entries
RENAULT, year 1979 : 1 entries
TOYOTA, year 1979 : 1 entries
VOLVO, year 1979 : 1 entries
AUDI, year 1980 : 1 entries
FORD, year 1980 : 1 entries
MITSUBISHI, year 1980 : 1 entries
VOLKSWAGEN, year 1980 : 1 entries
VOLVO, year 1980 : 1 entries
AUDI, year 1981 : 3 entries
BMW, year 1981 : 2 entries
CHEVROLET, year 1981 : 2 entries
OPEL, year 1981 : 1 entries
TOYOTA, year 1981 : 2 entries
BMW, year 1982 : 4 entries
CHEVROLET, year 1982 : 1 entries
TOYOTA, year 1982 : 4 entries
VOLKSWAGEN, year 1982 : 1 entries
AUDI, year 1983 : 3 entries
BMW, year 1983 : 4 entries
FORD, year 1983 : 1 entries
PORSCHE, year 1983 : 1 entries
TOYOTA, year 1983 : 2 entries
VOLKSWAGEN, year 1983 : 3 entries
VOLVO, year 1983 : 2 entries
AUDI, year 1984 : 8 entries
BMW, year 1984 : 2 entries
CHEVROLET, year 1984 : 3 entries
FORD, year 1984 : 1 entries
MAZDA, year 1984 : 2 entries
MITSUBISHI, year 1984 : 1 entries
OPEL, year 1984 : 1 entries
PORSCHE, year 1984 : 2 entries
SKODA, year 1984 : 1 entries
TOYOTA, year 1984 : 3 entries
VOLKSWAGEN, year 1984 : 1 entries
VOLVO, year 1984 : 1 entries
AUDI, year 1985 : 4 entries
BMW, year 1985 : 2 entries
FORD, year 1985 : 3 entries
HONDA, year 1985 : 2 entries
MAZDA, year 1985 : 2 entries
NISSAN, year 1985 : 2 entries
OPEL, year 1985 : 2 entries
TOYOTA, year 1985 : 2 entries
VOLKSWAGEN, year 1985 : 8 entries
VOLVO, year 1985 : 3 entries
AUDI, year 1986 : 3 entries
BMW, year 1986 : 4 entries
CHEVROLET, year 1986 : 1 entries
FORD, year 1986 : 2 entries
JEEP, year 1986 : 1 entries
MAZDA, year 1986 : 2 entries
NISSAN, year 1986 : 2 entries
OPEL, year 1986 : 1 entries
TOYOTA, year 1986 : 9 entries
VOLKSWAGEN, year 1986 : 7 entries
VOLVO, year 1986 : 4 entries
AUDI, year 1987 : 24 entries
BMW, year 1987 : 3 entries
FORD, year 1987 : 5 entries
JEEP, year 1987 : 2 entries
MAZDA, year 1987 : 2 entries
MITSUBISHI, year 1987 : 1 entries
NISSAN, year 1987 : 1 entries
OPEL, year 1987 : 4 entries
TOYOTA, year 1987 : 6 entries
VOLKSWAGEN, year 1987 : 5 entries
VOLVO, year 1987 : 2 entries
AUDI, year 1988 : 22 entries
BMW, year 1988 : 9 entries
CHEVROLET, year 1988 : 1 entries
FORD, year 1988 : 2 entries
HONDA, year 1988 : 2 entries
JEEP, year 1988 : 1 entries
MAZDA, year 1988 : 2 entries
MITSUBISHI, year 1988 : 2 entries
NISSAN, year 1988 : 3 entries
OPEL, year 1988 : 5 entries
PORSCHE, year 1988 : 1 entries
RENAULT, year 1988 : 1 entries
TOYOTA, year 1988 : 3 entries
VOLKSWAGEN, year 1988 : 26 entries
VOLVO, year 1988 : 1 entries
AUDI, year 1989 : 18 entries
BMW, year 1989 : 8 entries
FORD, year 1989 : 5 entries
HONDA, year 1989 : 2 entries
JEEP, year 1989 : 3 entries
MITSUBISHI, year 1989 : 3 entries
NISSAN, year 1989 : 9 entries
OPEL, year 1989 : 7 entries
PEUGEOT, year 1989 : 1 entries
SUZUKI, year 1989 : 1 entries
TOYOTA, year 1989 : 8 entries
VOLKSWAGEN, year 1989 : 25 entries
VOLVO, year 1989 : 3 entries
AUDI, year 1990 : 20 entries
BMW, year 1990 : 16 entries
CHEVROLET, year 1990 : 1 entries
CITROEN, year 1990 : 1 entries
FORD, year 1990 : 1 entries
HONDA, year 1990 : 1 entries
INFINITI, year 1990 : 1 entries
JEEP, year 1990 : 3 entries
MAZDA, year 1990 : 2 entries
MITSUBISHI, year 1990 : 1 entries
NISSAN, year 1990 : 6 entries
OPEL, year 1990 : 10 entries
SUZUKI, year 1990 : 2 entries
TOYOTA, year 1990 : 12 entries
VOLKSWAGEN, year 1990 : 37 entries
VOLKSWAGEN, year 1990 : 1 entries
VOLVO, year 1990 : 4 entries
AUDI, year 1991 : 38 entries
AUDI, year 1991 : 3 entries
BMW, year 1991 : 10 entries
CHEVROLET, year 1991 : 3 entries
FORD, year 1991 : 4 entries
HONDA, year 1991 : 3 entries
JEEP, year 1991 : 2 entries
MAZDA, year 1991 : 3 entries
MITSUBISHI, year 1991 : 6 entries
NISSAN, year 1991 : 10 entries
OPEL, year 1991 : 8 entries
PEUGEOT, year 1991 : 2 entries
SKODA, year 1991 : 2 entries
SUZUKI, year 1991 : 4 entries
TOYOTA, year 1991 : 33 entries
VOLKSWAGEN, year 1991 : 31 entries
VOLVO, year 1991 : 9 entries
AUDI, year 1992 : 25 entries
BMW, year 1992 : 14 entries
CHEVROLET, year 1992 : 4 entries
FORD, year 1992 : 6 entries
HONDA, year 1992 : 10 entries
INFINITI, year 1992 : 1 entries
JEEP, year 1992 : 5 entries
MAZDA, year 1992 : 11 entries
MITSUBISHI, year 1992 : 13 entries
NISSAN, year 1992 : 9 entries
OPEL, year 1992 : 10 entries
SUBARU, year 1992 : 3 entries
SUZUKI, year 1992 : 1 entries
TOYOTA, year 1992 : 37 entries
TOYOTA, year 1992 : 2 entries
VOLKSWAGEN, year 1992 : 37 entries
VOLKSWAGEN, year 1992 : 9 entries
VOLVO, year 1992 : 10 entries
AUDI, year 1993 : 9 entries
BMW, year 1993 : 9 entries
CHEVROLET, year 1993 : 5 entries
FORD, year 1993 : 11 entries
HONDA, year 1993 : 4 entries
JEEP, year 1993 : 16 entries
LEXUS, year 1993 : 1 entries
MAZDA, year 1993 : 6 entries
MITSUBISHI, year 1993 : 13 entries
NISSAN, year 1993 : 5 entries
OPEL, year 1993 : 16 entries
RENAULT, year 1993 : 1 entries
SKODA, year 1993 : 1 entries
SUBARU, year 1993 : 1 entries
SUZUKI, year 1993 : 2 entries
TOYOTA, year 1993 : 38 entries
TOYOTA, year 1993 : 18 entries
VOLKSWAGEN, year 1993 : 22 entries
VOLVO, year 1993 : 11 entries
AUDI, year 1994 : 15 entries
BMW, year 1994 : 8 entries
CHEVROLET, year 1994 : 5 entries
FORD, year 1994 : 18 entries
HONDA, year 1994 : 5 entries
HYUNDAI, year 1994 : 1 entries
JEEP, year 1994 : 3 entries
KIA, year 1994 : 4 entries
MAZDA, year 1994 : 8 entries
MITSUBISHI, year 1994 : 14 entries
NISSAN, year 1994 : 10 entries
OPEL, year 1994 : 14 entries
SUBARU, year 1994 : 3 entries
TOYOTA, year 1994 : 38 entries
TOYOTA, year 1994 : 2 entries
VOLKSWAGEN, year 1994 : 27 entries
VOLVO, year 1994 : 14 entries
AUDI, year 1995 : 16 entries
BMW, year 1995 : 6 entries
CHEVROLET, year 1995 : 7 entries
FORD, year 1995 : 22 entries
HONDA, year 1995 : 7 entries
HYUNDAI, year 1995 : 4 entries
JEEP, year 1995 : 9 entries
KIA, year 1995 : 1 entries
LEXUS, year 1995 : 1 entries
MAZDA, year 1995 : 9 entries
MITSUBISHI, year 1995 : 17 entries
NISSAN, year 1995 : 5 entries
OPEL, year 1995 : 9 entries
PEUGEOT, year 1995 : 3 entries
RENAULT, year 1995 : 1 entries
SUBARU, year 1995 : 9 entries
SUZUKI, year 1995 : 7 entries
TOYOTA, year 1995 : 34 entries
VOLKSWAGEN, year 1995 : 30 entries
VOLVO, year 1995 : 9 entries
AUDI, year 1996 : 9 entries
BMW, year 1996 : 18 entries
CHEVROLET, year 1996 : 10 entries
FORD, year 1996 : 18 entries
HONDA, year 1996 : 12 entries
HYUNDAI, year 1996 : 9 entries
INFINITI, year 1996 : 1 entries
JEEP, year 1996 : 6 entries
KIA, year 1996 : 3 entries
LEXUS, year 1996 : 2 entries
MAZDA, year 1996 : 5 entries
MITSUBISHI, year 1996 : 22 entries
NISSAN, year 1996 : 28 entries
OPEL, year 1996 : 19 entries
PEUGEOT, year 1996 : 1 entries
PORSCHE, year 1996 : 1 entries
RENAULT, year 1996 : 7 entries
SKODA, year 1996 : 7 entries
SUBARU, year 1996 : 1 entries
SUZUKI, year 1996 : 1 entries
TOYOTA, year 1996 : 37 entries
TOYOTA, year 1996 : 6 entries
VOLKSWAGEN, year 1996 : 23 entries
VOLVO, year 1996 : 8 entries
AUDI, year 1997 : 30 entries
BMW, year 1997 : 37 entries
BMW, year 1997 : 4 entries
CHEVROLET, year 1997 : 10 entries
FORD, year 1997 : 24 entries
HONDA, year 1997 : 22 entries
HYUNDAI, year 1997 : 9 entries
JEEP, year 1997 : 3 entries
KIA, year 1997 : 7 entries
LEXUS, year 1997 : 3 entries
MAZDA, year 1997 : 12 entries
MITSUBISHI, year 1997 : 26 entries
NISSAN, year 1997 : 34 entries
OPEL, year 1997 : 34 entries
PEUGEOT, year 1997 : 3 entries
RENAULT, year 1997 : 8 entries
SKODA, year 1997 : 22 entries
SUBARU, year 1997 : 12 entries
SUZUKI, year 1997 : 5 entries
TOYOTA, year 1997 : 37 entries
TOYOTA, year 1997 : 30 entries
VOLKSWAGEN, year 1997 : 37 entries
VOLVO, year 1997 : 14 entries
AUDI, year 1998 : 37 entries

AUDI, year 1998 : 3 entries
BMW, year 1998 : 37 entries
CHEVROLET, year 1998 : 5 entries
CITROEN, year 1998 : 3 entries
FORD, year 1998 : 14 entries
HONDA, year 1998 : 27 entries
HYUNDAI, year 1998 : 3 entries
INFINITI, year 1998 : 1 entries
JEEP, year 1998 : 7 entries
KIA, year 1998 : 11 entries
LEXUS, year 1998 : 4 entries
MAZDA, year 1998 : 15 entries
MITSUBISHI, year 1998 : 37 entries
MITSUBISHI, year 1998 : 3 entries
NISSAN, year 1998 : 38 entries
NISSAN, year 1998 : 6 entries
OPEL, year 1998 : 37 entries
OPEL, year 1998 : 1 entries
PEUGEOT, year 1998 : 9 entries
RENAULT, year 1998 : 10 entries
SKODA, year 1998 : 17 entries
SUBARU, year 1998 : 15 entries
SUZUKI, year 1998 : 15 entries
TOYOTA, year 1998 : 38 entries
TOYOTA, year 1998 : 31 entries
VOLKSWAGEN, year 1998 : 38 entries
VOLKSWAGEN, year 1998 : 24 entries
VOLVO, year 1998 : 17 entries
AUDI, year 1999 : 37 entries
AUDI, year 1999 : 3 entries
BMW, year 1999 : 37 entries
CHEVROLET, year 1999 : 3 entries
CITROEN, year 1999 : 1 entries
FORD, year 1999 : 12 entries
HONDA, year 1999 : 19 entries
HYUNDAI, year 1999 : 10 entries
JEEP, year 1999 : 10 entries
KIA, year 1999 : 2 entries
LEXUS, year 1999 : 7 entries
MAZDA, year 1999 : 14 entries
MITSUBISHI, year 1999 : 38 entries
MITSUBISHI, year 1999 : 13 entries
NISSAN, year 1999 : 37 entries
NISSAN, year 1999 : 12 entries
OPEL, year 1999 : 35 entries
PEUGEOT, year 1999 : 11 entries
RENAULT, year 1999 : 6 entries
SKODA, year 1999 : 6 entries
SUBARU, year 1999 : 19 entries
SUZUKI, year 1999 : 9 entries
TOYOTA, year 1999 : 37 entries
TOYOTA, year 1999 : 24 entries
VOLKSWAGEN, year 1999 : 37 entries
VOLKSWAGEN, year 1999 : 31 entries
VOLVO, year 1999 : 6 entries
AUDI, year 2000 : 37 entries
AUDI, year 2000 : 2 entries
BMW, year 2000 : 37 entries
BMW, year 2000 : 8 entries
CHEVROLET, year 2000 : 3 entries
CITROEN, year 2000 : 2 entries
FORD, year 2000 : 36 entries
HONDA, year 2000 : 20 entries
HYUNDAI, year 2000 : 12 entries
INFINITI, year 2000 : 3 entries
JEEP, year 2000 : 5 entries
KIA, year 2000 : 13 entries
LEXUS, year 2000 : 7 entries
MAZDA, year 2000 : 24 entries
MITSUBISHI, year 2000 : 37 entries
MITSUBISHI, year 2000 : 26 entries
NISSAN, year 2000 : 38 entries
NISSAN, year 2000 : 17 entries
OPEL, year 2000 : 38 entries
OPEL, year 2000 : 4 entries
PEUGEOT, year 2000 : 17 entries
PORSCHE, year 2000 : 2 entries
RENAULT, year 2000 : 10 entries
SKODA, year 2000 : 12 entries
SUBARU, year 2000 : 19 entries
SUZUKI, year 2000 : 15 entries
TOYOTA, year 2000 : 38 entries
TOYOTA, year 2000 : 9 entries
VOLKSWAGEN, year 2000 : 38 entries
VOLKSWAGEN, year 2000 : 23 entries
VOLVO, year 2000 : 6 entries
AUDI, year 2001 : 34 entries
BMW, year 2001 : 37 entries
BMW, year 2001 : 33 entries
CHEVROLET, year 2001 : 9 entries
CITROEN, year 2001 : 4 entries
FORD, year 2001 : 38 entries
FORD, year 2001 : 5 entries
HONDA, year 2001 : 30 entries
HYUNDAI, year 2001 : 25 entries
JEEP, year 2001 : 6 entries
KIA, year 2001 : 12 entries
LEXUS, year 2001 : 10 entries
MAZDA, year 2001 : 26 entries
MITSUBISHI, year 2001 : 38 entries
MITSUBISHI, year 2001 : 24 entries
NISSAN, year 2001 : 38 entries
NISSAN, year 2001 : 19 entries
OPEL, year 2001 : 25 entries
PEUGEOT, year 2001 : 24 entries
RENAULT, year 2001 : 21 entries
SKODA, year 2001 : 17 entries
SUBARU, year 2001 : 15 entries
SUZUKI, year 2001 : 12 entries
TOYOTA, year 2001 : 38 entries
TOYOTA, year 2001 : 36 entries
VOLKSWAGEN, year 2001 : 38 entries
VOLKSWAGEN, year 2001 : 34 entries
VOLVO, year 2001 : 21 entries
AUDI, year 2002 : 38 entries
AUDI, year 2002 : 19 entries
BMW, year 2002 : 38 entries
BMW, year 2002 : 32 entries
CHEVROLET, year 2002 : 6 entries
CITROEN, year 2002 : 10 entries
FORD, year 2002 : 37 entries
FORD, year 2002 : 9 entries
HONDA, year 2002 : 29 entries
HYUNDAI, year 2002 : 38 entries
HYUNDAI, year 2002 : 19 entries
INFINITI, year 2002 : 3 entries
JEEP, year 2002 : 2 entries
KIA, year 2002 : 31 entries
LEXUS, year 2002 : 12 entries
MINI, year 2002 : 3 entries
MAZDA, year 2002 : 18 entries
MITSUBISHI, year 2002 : 37 entries
MITSUBISHI, year 2002 : 37 entries
MITSUBISHI, year 2002 : 3 entries
NISSAN, year 2002 : 38 entries
NISSAN, year 2002 : 18 entries
OPEL, year 2002 : 18 entries
PEUGEOT, year 2002 : 27 entries
PORSCHE, year 2002 : 2 entries
RENAULT, year 2002 : 28 entries
SKODA, year 2002 : 33 entries
SUBARU, year 2002 : 14 entries
SUZUKI, year 2002 : 18 entries
TOYOTA, year 2002 : 37 entries
TOYOTA, year 2002 : 29 entries
VOLKSWAGEN, year 2002 : 37 entries
VOLKSWAGEN, year 2002 : 37 entries
VOLKSWAGEN, year 2002 : 3 entries
VOLVO, year 2002 : 15 entries
AUDI, year 2003 : 25 entries
BMW, year 2003 : 38 entries
BMW, year 2003 : 16 entries
CHEVROLET, year 2003 : 22 entries
CITROEN, year 2003 : 7 entries
FORD, year 2003 : 37 entries
FORD, year 2003 : 25 entries
HONDA, year 2003 : 26 entries
HYUNDAI, year 2003 : 38 entries
HYUNDAI, year 2003 : 7 entries
INFINITI, year 2003 : 15 entries
JEEP, year 2003 : 7 entries
KIA, year 2003 : 29 entries
LEXUS, year 2003 : 16 entries
MINI, year 2003 : 2 entries
MAZDA, year 2003 : 18 entries
MITSUBISHI, year 2003 : 38 entries
MITSUBISHI, year 2003 : 37 entries
MITSUBISHI, year 2003 : 14 entries
NISSAN, year 2003 : 38 entries
NISSAN, year 2003 : 37 entries
NISSAN, year 2003 : 1 entries
OPEL, year 2003 : 32 entries
PEUGEOT, year 2003 : 31 entries
PORSCHE, year 2003 : 10 entries
RENAULT, year 2003 : 21 entries
SKODA, year 2003 : 20 entries
SUBARU, year 2003 : 15 entries
SUZUKI, year 2003 : 19 entries
TOYOTA, year 2003 : 38 entries
TOYOTA, year 2003 : 32 entries
VOLKSWAGEN, year 2003 : 38 entries
VOLKSWAGEN, year 2003 : 16 entries
VOLVO, year 2003 : 30 entries
AUDI, year 2004 : 38 entries
AUDI, year 2004 : 9 entries
BMW, year 2004 : 38 entries
BMW, year 2004 : 37 entries
BMW, year 2004 : 21 entries
CHEVROLET, year 2004 : 38 entries
CHEVROLET, year 2004 : 31 entries
CITROEN, year 2004 : 18 entries
FORD, year 2004 : 37 entries
FORD, year 2004 : 37 entries
FORD, year 2004 : 13 entries
HONDA, year 2004 : 11 entries
HYUNDAI, year 2004 : 38 entries
HYUNDAI, year 2004 : 37 entries
HYUNDAI, year 2004 : 31 entries
INFINITI, year 2004 : 10 entries
JEEP, year 2004 : 15 entries
KIA, year 2004 : 37 entries
KIA, year 2004 : 3 entries
LEXUS, year 2004 : 12 entries
MINI, year 2004 : 1 entries
MAZDA, year 2004 : 38 entries
MAZDA, year 2004 : 11 entries
MITSUBISHI, year 2004 : 38 entries
MITSUBISHI, year 2004 : 37 entries
MITSUBISHI, year 2004 : 33 entries
NISSAN, year 2004 : 38 entries
NISSAN, year 2004 : 37 entries
NISSAN, year 2004 : 16 entries
OPEL, year 2004 : 32 entries
PEUGEOT, year 2004 : 28 entries
PORSCHE, year 2004 : 27 entries
RENAULT, year 2004 : 37 entries
RENAULT, year 2004 : 2 entries
SKODA, year 2004 : 13 entries
SUBARU, year 2004 : 19 entries
SUZUKI, year 2004 : 13 entries
TOYOTA, year 2004 : 38 entries
TOYOTA, year 2004 : 19 entries
VOLKSWAGEN, year 2004 : 37 entries
VOLKSWAGEN, year 2004 : 34 entries
VOLVO, year 2004 : 35 entries
AUDI, year 2005 : 37 entries
AUDI, year 2005 : 10 entries
BMW, year 2005 : 38 entries
BMW, year 2005 : 37 entries
BMW, year 2005 : 11 entries
CHEVROLET, year 2005 : 37 entries
CHEVROLET, year 2005 : 37 entries
CHEVROLET, year 2005 : 24 entries
CITROEN, year 2005 : 21 entries
FORD, year 2005 : 38 entries
FORD, year 2005 : 37 entries
FORD, year 2005 : 32 entries
HONDA, year 2005 : 16 entries
HYUNDAI, year 2005 : 37 entries
HYUNDAI, year 2005 : 37 entries
HYUNDAI, year 2005 : 37 entries
HYUNDAI, year 2005 : 6 entries
INFINITI, year 2005 : 13 entries
JEEP, year 2005 : 7 entries
KIA, year 2005 : 38 entries
KIA, year 2005 : 20 entries
LEXUS, year 2005 : 19 entries
MINI, year 2005 : 3 entries
MAZDA, year 2005 : 37 entries
MAZDA, year 2005 : 33 entries
MITSUBISHI, year 2005 : 38 entries
MITSUBISHI, year 2005 : 37 entries
MITSUBISHI, year 2005 : 37 entries
MITSUBISHI, year 2005 : 19 entries
NISSAN, year 2005 : 38 entries
NISSAN, year 2005 : 37 entries
NISSAN, year 2005 : 22 entries
OPEL, year 2005 : 14 entries
PEUGEOT, year 2005 : 21 entries
PORSCHE, year 2005 : 16 entries
RENAULT, year 2005 : 37 entries
RENAULT, year 2005 : 2 entries
SKODA, year 2005 : 13 entries
SUBARU, year 2005 : 18 entries
SUZUKI, year 2005 : 23 entries
TOYOTA, year 2005 : 38 entries

TOYOTA, year 2005 : 17 entries
VOLKSWAGEN, year 2005 : 38 entries
VOLKSWAGEN, year 2005 : 37 entries
VOLKSWAGEN, year 2005 : 4 entries
VOLVO, year 2005 : 22 entries
AUDI, year 2006 : 37 entries
AUDI, year 2006 : 37 entries
AUDI, year 2006 : 11 entries
BMW, year 2006 : 37 entries
BMW, year 2006 : 22 entries
CHEVROLET, year 2006 : 38 entries
CHEVROLET, year 2006 : 37 entries
CHEVROLET, year 2006 : 37 entries
CHEVROLET, year 2006 : 37 entries
CHEVROLET, year 2006 : 37 entries
CITROEN, year 2006 : 37 entries
CITROEN, year 2006 : 2 entries
FORD, year 2006 : 38 entries
FORD, year 2006 : 38 entries
FORD, year 2006 : 37 entries
FORD, year 2006 : 37 entries
FORD, year 2006 : 37 entries
FORD, year 2006 : 37 entries
FORD, year 2006 : 37 entries
HONDA, year 2006 : 32 entries
HYUNDAI, year 2006 : 38 entries
HYUNDAI, year 2006 : 37 entries
HYUNDAI, year 2006 : 37 entries
HYUNDAI, year 2006 : 19 entries
INFINITI, year 2006 : 15 entries
JEEP, year 2006 : 9 entries
KIA, year 2006 : 38 entries
KIA, year 2006 : 37 entries
KIA, year 2006 : 34 entries
LEXUS, year 2006 : 25 entries
MINI, year 2006 : 2 entries
MAZDA, year 2006 : 38 entries
MAZDA, year 2006 : 37 entries
MAZDA, year 2006 : 22 entries
MITSUBISHI, year 2006 : 38 entries
MITSUBISHI, year 2006 : 37 entries
MITSUBISHI, year 2006 : 37 entries
MITSUBISHI, year 2006 : 24 entries
NISSAN, year 2006 : 38 entries
NISSAN, year 2006 : 37 entries
NISSAN, year 2006 : 37 entries
NISSAN, year 2006 : 36 entries
OPEL, year 2006 : 38 entries
OPEL, year 2006 : 31 entries
PEUGEOT, year 2006 : 37 entries
PEUGEOT, year 2006 : 11 entries
PORSCHE, year 2006 : 7 entries
RENAULT, year 2006 : 38 entries
RENAULT, year 2006 : 37 entries
RENAULT, year 2006 : 8 entries
SKODA, year 2006 : 29 entries
SUBARU, year 2006 : 37 entries
SUZUKI, year 2006 : 28 entries
TOYOTA, year 2006 : 38 entries
TOYOTA, year 2006 : 37 entries
TOYOTA, year 2006 : 24 entries
VOLKSWAGEN, year 2006 : 38 entries
VOLKSWAGEN, year 2006 : 37 entries
VOLKSWAGEN, year 2006 : 21 entries
VOLVO, year 2006 : 35 entries
VOLVO, year 2006 : 1 entries
AUDI, year 2007 : 37 entries
AUDI, year 2007 : 37 entries
AUDI, year 2007 : 37 entries
AUDI, year 2007 : 5 entries
BMW, year 2007 : 38 entries
BMW, year 2007 : 37 entries
BMW, year 2007 : 37 entries
BMW, year 2007 : 37 entries
BMW, year 2007 : 33 entries
CHEVROLET, year 2007 : 38 entries
CHEVROLET, year 2007 : 37 entries
CHEVROLET, year 2007 : 37 entries
CHEVROLET, year 2007 : 37 entries
CHEVROLET, year 2007 : 37 entries
CHEVROLET, year 2007 : 37 entries
CHEVROLET, year 2007 : 37 entries
CHEVROLET, year 2007 : 7 entries
CITROEN, year 2007 : 38 entries
FORD, year 2007 : 38 entries
FORD, year 2007 : 37 entries
FORD, year 2007 : 37 entries
FORD, year 2007 : 37 entries
FORD, year 2007 : 37 entries
FORD, year 2007 : 37 entries
FORD, year 2007 : 37 entries
FORD, year 2007 : 19 entries
HONDA, year 2007 : 38 entries
HONDA, year 2007 : 37 entries
HYUNDAI, year 2007 : 38 entries
HYUNDAI, year 2007 : 37 entries
HYUNDAI, year 2007 : 37 entries
HYUNDAI, year 2007 : 37 entries
HYUNDAI, year 2007 : 15 entries
INFINITI, year 2007 : 37 entries
INFINITI, year 2007 : 8 entries
JEEP, year 2007 : 10 entries
KIA, year 2007 : 38 entries
KIA, year 2007 : 37 entries
KIA, year 2007 : 37 entries
KIA, year 2007 : 11 entries
LEXUS, year 2007 : 25 entries
MINI, year 2007 : 5 entries
MAZDA, year 2007 : 38 entries
MAZDA, year 2007 : 37 entries
MAZDA, year 2007 : 37 entries
MAZDA, year 2007 : 33 entries
MITSUBISHI, year 2007 : 38 entries
MITSUBISHI, year 2007 : 37 entries
MITSUBISHI, year 2007 : 37 entries
MITSUBISHI, year 2007 : 37 entries
MITSUBISHI, year 2007 : 37 entries
MITSUBISHI, year 2007 : 4 entries
NISSAN, year 2007 : 38 entries
NISSAN, year 2007 : 38 entries
NISSAN, year 2007 : 37 entries
NISSAN, year 2007 : 37 entries
NISSAN, year 2007 : 31 entries
OPEL, year 2007 : 38 entries
OPEL, year 2007 : 37 entries
OPEL, year 2007 : 37 entries
OPEL, year 2007 : 37 entries
OPEL, year 2007 : 37 entries
OPEL, year 2007 : 26 entries
PEUGEOT, year 2007 : 38 entries
PEUGEOT, year 2007 : 33 entries
PORSCHE, year 2007 : 32 entries
RENAULT, year 2007 : 38 entries
RENAULT, year 2007 : 37 entries
RENAULT, year 2007 : 23 entries
SKODA, year 2007 : 37 entries
SKODA, year 2007 : 34 entries
SUBARU, year 2007 : 38 entries
SUBARU, year 2007 : 12 entries
SUZUKI, year 2007 : 38 entries
SUZUKI, year 2007 : 24 entries
TOYOTA, year 2007 : 38 entries
TOYOTA, year 2007 : 37 entries
TOYOTA, year 2007 : 37 entries
TOYOTA, year 2007 : 37 entries
TOYOTA, year 2007 : 22 entries
VOLKSWAGEN, year 2007 : 38 entries
VOLKSWAGEN, year 2007 : 37 entries
VOLKSWAGEN, year 2007 : 37 entries
VOLKSWAGEN, year 2007 : 32 entries
VOLVO, year 2007 : 38 entries
VOLVO, year 2007 : 37 entries
VOLVO, year 2007 : 12 entries
AUDI, year 2008 : 38 entries
AUDI, year 2008 : 37 entries
AUDI, year 2008 : 37 entries
AUDI, year 2008 : 27 entries
BMW, year 2008 : 38 entries
BMW, year 2008 : 37 entries
BMW, year 2008 : 37 entries
BMW, year 2008 : 37 entries
BMW, year 2008 : 37 entries
BMW, year 2008 : 30 entries
CHEVROLET, year 2008 : 38 entries
CHEVROLET, year 2008 : 37 entries
CHEVROLET, year 2008 : 37 entries
CHEVROLET, year 2008 : 37 entries
CHEVROLET, year 2008 : 37 entries
CHEVROLET, year 2008 : 37 entries
CHEVROLET, year 2008 : 37 entries
CHEVROLET, year 2008 : 37 entries
CHEVROLET, year 2008 : 10 entries
CITROEN, year 2008 : 38 entries
CITROEN, year 2008 : 8 entries
FORD, year 2008 : 38 entries
FORD, year 2008 : 37 entries
FORD, year 2008 : 37 entries
FORD, year 2008 : 37 entries
FORD, year 2008 : 37 entries
FORD, year 2008 : 37 entries
FORD, year 2008 : 37 entries
FORD, year 2008 : 37 entries
FORD, year 2008 : 11 entries
HONDA, year 2008 : 38 entries
HONDA, year 2008 : 37 entries
HONDA, year 2008 : 37 entries
HONDA, year 2008 : 32 entries
HYUNDAI, year 2008 : 38 entries
HYUNDAI, year 2008 : 37 entries
HYUNDAI, year 2008 : 37 entries
HYUNDAI, year 2008 : 37 entries
HYUNDAI, year 2008 : 37 entries
HYUNDAI, year 2008 : 37 entries
HYUNDAI, year 2008 : 37 entries
HYUNDAI, year 2008 : 35 entries
INFINITI, year 2008 : 37 entries
INFINITI, year 2008 : 29 entries
JEEP, year 2008 : 13 entries
KIA, year 2008 : 38 entries
KIA, year 2008 : 37 entries
KIA, year 2008 : 37 entries
KIA, year 2008 : 20 entries
LEXUS, year 2008 : 37 entries
LEXUS, year 2008 : 22 entries
MINI, year 2008 : 3 entries
MAZDA, year 2008 : 38 entries
MAZDA, year 2008 : 37 entries
MAZDA, year 2008 : 37 entries
MAZDA, year 2008 : 37 entries
MAZDA, year 2008 : 37 entries
MAZDA, year 2008 : 26 entries
MITSUBISHI, year 2008 : 38 entries
MITSUBISHI, year 2008 : 37 entries
MITSUBISHI, year 2008 : 37 entries
MITSUBISHI, year 2008 : 25 entries
NISSAN, year 2008 : 38 entries
NISSAN, year 2008 : 37 entries
NISSAN, year 2008 : 37 entries
NISSAN, year 2008 : 37 entries
NISSAN, year 2008 : 37 entries
NISSAN, year 2008 : 37 entries
NISSAN, year 2008 : 29 entries
OPEL, year 2008 : 38 entries
OPEL, year 2008 : 37 entries
OPEL, year 2008 : 37 entries
OPEL, year 2008 : 37 entries
OPEL, year 2008 : 37 entries
OPEL, year 2008 : 37 entries
OPEL, year 2008 : 37 entries
OPEL, year 2008 : 9 entries
PEUGEOT, year 2008 : 38 entries
PEUGEOT, year 2008 : 37 entries
PEUGEOT, year 2008 : 37 entries
PEUGEOT, year 2008 : 7 entries
PORSCHE, year 2008 : 28 entries
RENAULT, year 2008 : 38 entries
RENAULT, year 2008 : 37 entries
RENAULT, year 2008 : 37 entries
RENAULT, year 2008 : 20 entries
SKODA, year 2008 : 37 entries
SKODA, year 2008 : 34 entries
SUBARU, year 2008 : 37 entries
SUZUKI, year 2008 : 37 entries
SUZUKI, year 2008 : 37 entries
SUZUKI, year 2008 : 16 entries
TOYOTA, year 2008 : 38 entries
TOYOTA, year 2008 : 37 entries
TOYOTA, year 2008 : 37 entries
TOYOTA, year 2008 : 37 entries
TOYOTA, year 2008 : 37 entries
TOYOTA, year 2008 : 37 entries
VOLKSWAGEN, year 2008 : 38 entries
VOLKSWAGEN, year 2008 : 37 entries
VOLKSWAGEN, year 2008 : 37 entries
VOLKSWAGEN, year 2008 : 37 entries
VOLKSWAGEN, year 2008 : 37 entries
VOLKSWAGEN, year 2008 : 37 entries
VOLKSWAGEN, year 2008 : 18 entries
VOLVO, year 2008 : 38 entries
VOLVO, year 2008 : 37 entries
VOLVO, year 2008 : 17 entries
AUDI, year 2009 : 38 entries
AUDI, year 2009 : 37 entries
AUDI, year 2009 : 31 entries
BMW, year 2009 : 37 entries

BMW, year 2009 : 37 entries
BMW, year 2009 : 37 entries
BMW, year 2009 : 37 entries
BMW, year 2009 : 12 entries
CHEVROLET, year 2009 : 38 entries
CHEVROLET, year 2009 : 37 entries
CHEVROLET, year 2009 : 25 entries
CITROEN, year 2009 : 33 entries
FORD, year 2009 : 37 entries
FORD, year 2009 : 37 entries
FORD, year 2009 : 25 entries
HONDA, year 2009 : 17 entries
HYUNDAI, year 2009 : 37 entries
HYUNDAI, year 2009 : 37 entries
HYUNDAI, year 2009 : 5 entries
INFINITI, year 2009 : 19 entries
KIA, year 2009 : 38 entries
KIA, year 2009 : 37 entries
KIA, year 2009 : 34 entries
LEXUS, year 2009 : 15 entries
MINI, year 2009 : 5 entries
MAZDA, year 2009 : 10 entries
MITSUBISHI, year 2009 : 13 entries
NISSAN, year 2009 : 38 entries
NISSAN, year 2009 : 9 entries
OPEL, year 2009 : 37 entries
OPEL, year 2009 : 1 entries
PEUGEOT, year 2009 : 37 entries
PEUGEOT, year 2009 : 20 entries
PORSCHE, year 2009 : 11 entries
RENAULT, year 2009 : 38 entries
RENAULT, year 2009 : 21 entries
SKODA, year 2009 : 37 entries
SKODA, year 2009 : 14 entries
SUBARU, year 2009 : 7 entries
SUZUKI, year 2009 : 6 entries
TOYOTA, year 2009 : 37 entries
TOYOTA, year 2009 : 24 entries
VOLKSWAGEN, year 2009 : 37 entries
VOLKSWAGEN, year 2009 : 37 entries
VOLKSWAGEN, year 2009 : 37 entries
VOLKSWAGEN, year 2009 : 5 entries
VOLVO, year 2009 : 24 entries
AUDI, year 2010 : 38 entries
AUDI, year 2010 : 37 entries
AUDI, year 2010 : 37 entries
AUDI, year 2010 : 29 entries
BMW, year 2010 : 38 entries
BMW, year 2010 : 37 entries
BMW, year 2010 : 37 entries
BMW, year 2010 : 37 entries
BMW, year 2010 : 37 entries
BMW, year 2010 : 3 entries
CHEVROLET, year 2010 : 38 entries
CHEVROLET, year 2010 : 37 entries
CHEVROLET, year 2010 : 37 entries
CHEVROLET, year 2010 : 16 entries
CITROEN, year 2010 : 37 entries
CITROEN, year 2010 : 30 entries
FORD, year 2010 : 38 entries
FORD, year 2010 : 37 entries
FORD, year 2010 : 37 entries
FORD, year 2010 : 37 entries
FORD, year 2010 : 32 entries
HONDA, year 2010 : 24 entries
HYUNDAI, year 2010 : 38 entries
HYUNDAI, year 2010 : 37 entries
HYUNDAI, year 2010 : 37 entries
HYUNDAI, year 2010 : 37 entries
HYUNDAI, year 2010 : 1 entries
INFINITI, year 2010 : 35 entries
JEEP, year 2010 : 6 entries
KIA, year 2010 : 38 entries
KIA, year 2010 : 37 entries
KIA, year 2010 : 37 entries
KIA, year 2010 : 37 entries
KIA, year 2010 : 28 entries
LEXUS, year 2010 : 38 entries
LEXUS, year 2010 : 3 entries
MINI, year 2010 : 6 entries
MAZDA, year 2010 : 38 entries
MAZDA, year 2010 : 31 entries
MITSUBISHI, year 2010 : 38 entries
MITSUBISHI, year 2010 : 29 entries
NISSAN, year 2010 : 38 entries
NISSAN, year 2010 : 37 entries
NISSAN, year 2010 : 37 entries
NISSAN, year 2010 : 37 entries
NISSAN, year 2010 : 37 entries
NISSAN, year 2010 : 4 entries
OPEL, year 2010 : 38 entries
OPEL, year 2010 : 37 entries
OPEL, year 2010 : 37 entries
OPEL, year 2010 : 35 entries
PEUGEOT, year 2010 : 38 entries
PEUGEOT, year 2010 : 37 entries
PEUGEOT, year 2010 : 37 entries
PEUGEOT, year 2010 : 7 entries
PORSCHE, year 2010 : 22 entries
RENAULT, year 2010 : 38 entries
RENAULT, year 2010 : 37 entries
RENAULT, year 2010 : 37 entries
RENAULT, year 2010 : 8 entries
SKODA, year 2010 : 37 entries
SKODA, year 2010 : 37 entries
SKODA, year 2010 : 18 entries
SUBARU, year 2010 : 8 entries
SUZUKI, year 2010 : 38 entries
SUZUKI, year 2010 : 13 entries
TOYOTA, year 2010 : 38 entries
TOYOTA, year 2010 : 37 entries
TOYOTA, year 2010 : 37 entries
TOYOTA, year 2010 : 1 entries
VOLKSWAGEN, year 2010 : 38 entries
VOLKSWAGEN, year 2010 : 37 entries
VOLKSWAGEN, year 2010 : 37 entries
VOLKSWAGEN, year 2010 : 37 entries
VOLKSWAGEN, year 2010 : 37 entries
VOLKSWAGEN, year 2010 : 35 entries
VOLVO, year 2010 : 37 entries
VOLVO, year 2010 : 34 entries
AUDI, year 2011 : 38 entries
AUDI, year 2011 : 37 entries
AUDI, year 2011 : 37 entries
AUDI, year 2011 : 37 entries
AUDI, year 2011 : 17 entries
BMW, year 2011 : 38 entries
BMW, year 2011 : 37 entries
BMW, year 2011 : 37 entries
BMW, year 2011 : 37 entries
BMW, year 2011 : 37 entries
BMW, year 2011 : 37 entries
BMW, year 2011 : 28 entries
CHEVROLET, year 2011 : 38 entries
CHEVROLET, year 2011 : 37 entries
CHEVROLET, year 2011 : 37 entries
CHEVROLET, year 2011 : 37 entries
CHEVROLET, year 2011 : 37 entries
CHEVROLET, year 2011 : 15 entries
CITROEN, year 2011 : 38 entries
CITROEN, year 2011 : 37 entries
CITROEN, year 2011 : 2 entries
FORD, year 2011 : 38 entries
FORD, year 2011 : 37 entries
FORD, year 2011 : 37 entries
FORD, year 2011 : 37 entries
FORD, year 2011 : 37 entries
FORD, year 2011 : 6 entries
HONDA, year 2011 : 36 entries
HYUNDAI, year 2011 : 38 entries
HYUNDAI, year 2011 : 37 entries
HYUNDAI, year 2011 : 37 entries
HYUNDAI, year 2011 : 37 entries
HYUNDAI, year 2011 : 37 entries
HYUNDAI, year 2011 : 37 entries
HYUNDAI, year 2011 : 11 entries
INFINITI, year 2011 : 38 entries
INFINITI, year 2011 : 18 entries
JEEP, year 2011 : 20 entries
KIA, year 2011 : 38 entries
KIA, year 2011 : 37 entries
KIA, year 2011 : 37 entries
KIA, year 2011 : 37 entries
KIA, year 2011 : 37 entries
KIA, year 2011 : 37 entries
KIA, year 2011 : 22 entries
LEXUS, year 2011 : 33 entries
MINI, year 2011 : 28 entries
MAZDA, year 2011 : 38 entries
MAZDA, year 2011 : 37 entries
MAZDA, year 2011 : 37 entries
MAZDA, year 2011 : 11 entries
MITSUBISHI, year 2011 : 37 entries
MITSUBISHI, year 2011 : 37 entries
MITSUBISHI, year 2011 : 13 entries
NISSAN, year 2011 : 38 entries
NISSAN, year 2011 : 37 entries
NISSAN, year 2011 : 37 entries
NISSAN, year 2011 : 37 entries
NISSAN, year 2011 : 37 entries
NISSAN, year 2011 : 37 entries
NISSAN, year 2011 : 37 entries
NISSAN, year 2011 : 7 entries
OPEL, year 2011 : 37 entries
OPEL, year 2011 : 37 entries
OPEL, year 2011 : 37 entries
OPEL, year 2011 : 37 entries
OPEL, year 2011 : 37 entries
OPEL, year 2011 : 37 entries
OPEL, year 2011 : 12 entries
PEUGEOT, year 2011 : 38 entries
PEUGEOT, year 2011 : 37 entries
PEUGEOT, year 2011 : 23 entries
PORSCHE, year 2011 : 29 entries
RENAULT, year 2011 : 38 entries
RENAULT, year 2011 : 37 entries
RENAULT, year 2011 : 37 entries
RENAULT, year 2011 : 37 entries
RENAULT, year 2011 : 2 entries
SKODA, year 2011 : 38 entries
SKODA, year 2011 : 37 entries
SKODA, year 2011 : 37 entries
SKODA, year 2011 : 37 entries
SKODA, year 2011 : 22 entries
SUBARU, year 2011 : 21 entries
SUZUKI, year 2011 : 37 entries
SUZUKI, year 2011 : 14 entries
TOYOTA, year 2011 : 38 entries
TOYOTA, year 2011 : 37 entries
TOYOTA, year 2011 : 37 entries
TOYOTA, year 2011 : 37 entries
TOYOTA, year 2011 : 20 entries
VOLKSWAGEN, year 2011 : 38 entries
VOLKSWAGEN, year 2011 : 37 entries
VOLKSWAGEN, year 2011 : 37 entries
VOLKSWAGEN, year 2011 : 37 entries
VOLKSWAGEN, year 2011 : 37 entries
VOLKSWAGEN, year 2011 : 37 entries
VOLKSWAGEN, year 2011 : 37 entries
VOLKSWAGEN, year 2011 : 37 entries
VOLKSWAGEN, year 2011 : 11 entries
VOLVO, year 2011 : 38 entries
VOLVO, year 2011 : 37 entries
VOLVO, year 2011 : 27 entries
AUDI, year 2012 : 38 entries
AUDI, year 2012 : 37 entries
AUDI, year 2012 : 37 entries
AUDI, year 2012 : 37 entries
AUDI, year 2012 : 37 entries
AUDI, year 2012 : 26 entries
BMW, year 2012 : 38 entries
BMW, year 2012 : 37 entries
BMW, year 2012 : 37 entries
BMW, year 2012 : 37 entries
BMW, year 2012 : 37 entries
BMW, year 2012 : 37 entries
BMW, year 2012 : 37 entries
BMW, year 2012 : 37 entries
BMW, year 2012 : 2 entries
CHEVROLET, year 2012 : 38 entries
CHEVROLET, year 2012 : 37 entries
CHEVROLET, year 2012 : 37 entries
CHEVROLET, year 2012 : 37 entries
CHEVROLET, year 2012 : 37 entries
CHEVROLET, year 2012 : 37 entries
CHEVROLET, year 2012 : 37 entries
CHEVROLET, year 2012 : 13 entries
CITROEN, year 2012 : 38 entries
CITROEN, year 2012 : 37 entries
CITROEN, year 2012 : 15 entries
FORD, year 2012 : 38 entries
FORD, year 2012 : 37 entries
FORD, year 2012 : 37 entries
FORD, year 2012 : 37 entries
FORD, year 2012 : 37 entries
FORD, year 2012 : 28 entries
HONDA, year 2012 : 38 entries
HONDA, year 2012 : 9 entries
HYUNDAI, year 2012 : 38 entries
HYUNDAI, year 2012 : 37 entries
HYUNDAI, year 2012 : 37 entries
HYUNDAI, year 2012 : 37 entries
HYUNDAI, year 2012 : 37 entries
HYUNDAI, year 2012 : 37 entries
HYUNDAI, year 2012 : 14 entries
INFINITI, year 2012 : 38 entries
INFINITI, year 2012 : 24 entries

JEEP, year 2012 : 37 entries
JEEP, year 2012 : 29 entries
KIA, year 2012 : 38 entries
KIA, year 2012 : 37 entries
KIA, year 2012 : 37 entries
KIA, year 2012 : 37 entries
KIA, year 2012 : 37 entries
KIA, year 2012 : 37 entries
KIA, year 2012 : 37 entries
KIA, year 2012 : 21 entries
LEXUS, year 2012 : 37 entries
LEXUS, year 2012 : 7 entries
MINI, year 2012 : 26 entries
MAZDA, year 2012 : 38 entries
MAZDA, year 2012 : 29 entries
MITSUBISHI, year 2012 : 38 entries
MITSUBISHI, year 2012 : 37 entries
MITSUBISHI, year 2012 : 37 entries
MITSUBISHI, year 2012 : 22 entries
NISSAN, year 2012 : 38 entries
NISSAN, year 2012 : 37 entries
NISSAN, year 2012 : 37 entries
NISSAN, year 2012 : 37 entries
NISSAN, year 2012 : 37 entries
NISSAN, year 2012 : 37 entries
NISSAN, year 2012 : 37 entries
NISSAN, year 2012 : 37 entries
NISSAN, year 2012 : 23 entries
OPEL, year 2012 : 37 entries
OPEL, year 2012 : 37 entries
OPEL, year 2012 : 37 entries
OPEL, year 2012 : 37 entries
OPEL, year 2012 : 37 entries
OPEL, year 2012 : 37 entries
OPEL, year 2012 : 30 entries
PEUGEOT, year 2012 : 38 entries
PEUGEOT, year 2012 : 37 entries
PEUGEOT, year 2012 : 37 entries
PEUGEOT, year 2012 : 33 entries
PORSCHE, year 2012 : 26 entries
RENAULT, year 2012 : 38 entries
RENAULT, year 2012 : 37 entries
RENAULT, year 2012 : 37 entries
RENAULT, year 2012 : 37 entries
RENAULT, year 2012 : 21 entries
SKODA, year 2012 : 38 entries
SKODA, year 2012 : 37 entries
SKODA, year 2012 : 37 entries
SKODA, year 2012 : 37 entries
SKODA, year 2012 : 37 entries
SKODA, year 2012 : 37 entries
SUBARU, year 2012 : 32 entries
SUZUKI, year 2012 : 30 entries
TOYOTA, year 2012 : 38 entries
TOYOTA, year 2012 : 37 entries
TOYOTA, year 2012 : 37 entries
TOYOTA, year 2012 : 37 entries
TOYOTA, year 2012 : 5 entries
VOLKSWAGEN, year 2012 : 38 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 37 entries
VOLKSWAGEN, year 2012 : 32 entries
VOLVO, year 2012 : 37 entries
VOLVO, year 2012 : 37 entries
VOLVO, year 2012 : 10 entries
AUDI, year 2013 : 38 entries
AUDI, year 2013 : 37 entries
AUDI, year 2013 : 37 entries
AUDI, year 2013 : 37 entries
AUDI, year 2013 : 37 entries
AUDI, year 2013 : 7 entries
BMW, year 2013 : 38 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 37 entries
BMW, year 2013 : 6 entries
CHEVROLET, year 2013 : 38 entries
CHEVROLET, year 2013 : 37 entries
CHEVROLET, year 2013 : 37 entries
CHEVROLET, year 2013 : 37 entries
CHEVROLET, year 2013 : 37 entries
CHEVROLET, year 2013 : 37 entries
CHEVROLET, year 2013 : 2 entries
CITROEN, year 2013 : 37 entries
CITROEN, year 2013 : 31 entries
FORD, year 2013 : 38 entries
FORD, year 2013 : 37 entries
FORD, year 2013 : 37 entries
FORD, year 2013 : 37 entries
FORD, year 2013 : 37 entries
FORD, year 2013 : 37 entries
FORD, year 2013 : 8 entries
HONDA, year 2013 : 38 entries
HONDA, year 2013 : 24 entries
HYUNDAI, year 2013 : 38 entries
HYUNDAI, year 2013 : 37 entries
HYUNDAI, year 2013 : 37 entries
HYUNDAI, year 2013 : 37 entries
HYUNDAI, year 2013 : 37 entries
HYUNDAI, year 2013 : 37 entries
HYUNDAI, year 2013 : 22 entries
INFINITI, year 2013 : 38 entries
INFINITI, year 2013 : 18 entries
JEEP, year 2013 : 28 entries
KIA, year 2013 : 38 entries
KIA, year 2013 : 37 entries
KIA, year 2013 : 37 entries
KIA, year 2013 : 37 entries
KIA, year 2013 : 37 entries
KIA, year 2013 : 37 entries
KIA, year 2013 : 37 entries
KIA, year 2013 : 19 entries
LEXUS, year 2013 : 38 entries
LEXUS, year 2013 : 7 entries
MINI, year 2013 : 19 entries
MAZDA, year 2013 : 37 entries
MAZDA, year 2013 : 37 entries
MAZDA, year 2013 : 17 entries
MITSUBISHI, year 2013 : 37 entries
MITSUBISHI, year 2013 : 37 entries
MITSUBISHI, year 2013 : 37 entries
MITSUBISHI, year 2013 : 9 entries
NISSAN, year 2013 : 38 entries
NISSAN, year 2013 : 37 entries
NISSAN, year 2013 : 37 entries
NISSAN, year 2013 : 37 entries
NISSAN, year 2013 : 37 entries
NISSAN, year 2013 : 37 entries
NISSAN, year 2013 : 29 entries
OPEL, year 2013 : 37 entries
OPEL, year 2013 : 37 entries
OPEL, year 2013 : 37 entries
OPEL, year 2013 : 37 entries
OPEL, year 2013 : 37 entries
OPEL, year 2013 : 28 entries
PEUGEOT, year 2013 : 37 entries
PEUGEOT, year 2013 : 32 entries
PORSCHE, year 2013 : 37 entries
PORSCHE, year 2013 : 12 entries
RENAULT, year 2013 : 38 entries
RENAULT, year 2013 : 37 entries
RENAULT, year 2013 : 37 entries
RENAULT, year 2013 : 37 entries
RENAULT, year 2013 : 37 entries
RENAULT, year 2013 : 15 entries
SKODA, year 2013 : 38 entries
SKODA, year 2013 : 37 entries
SKODA, year 2013 : 37 entries
SKODA, year 2013 : 37 entries
SKODA, year 2013 : 23 entries
SUBARU, year 2013 : 26 entries
SUZUKI, year 2013 : 31 entries
TOYOTA, year 2013 : 38 entries
TOYOTA, year 2013 : 37 entries
TOYOTA, year 2013 : 37 entries
TOYOTA, year 2013 : 37 entries
TOYOTA, year 2013 : 37 entries
TOYOTA, year 2013 : 17 entries
VOLKSWAGEN, year 2013 : 38 entries
VOLKSWAGEN, year 2013 : 38 entries
VOLKSWAGEN, year 2013 : 37 entries
VOLKSWAGEN, year 2013 : 37 entries
VOLKSWAGEN, year 2013 : 37 entries
VOLKSWAGEN, year 2013 : 37 entries
VOLKSWAGEN, year 2013 : 37 entries
VOLKSWAGEN, year 2013 : 37 entries
VOLKSWAGEN, year 2013 : 12 entries
VOLVO, year 2013 : 37 entries
VOLVO, year 2013 : 26 entries
AUDI, year 2014 : 38 entries
AUDI, year 2014 : 37 entries
AUDI, year 2014 : 37 entries
AUDI, year 2014 : 37 entries
AUDI, year 2014 : 15 entries
BMW, year 2014 : 38 entries
BMW, year 2014 : 37 entries
BMW, year 2014 : 37 entries
BMW, year 2014 : 37 entries
BMW, year 2014 : 37 entries
BMW, year 2014 : 37 entries
BMW, year 2014 : 37 entries
BMW, year 2014 : 14 entries
CHEVROLET, year 2014 : 38 entries
CHEVROLET, year 2014 : 37 entries
CHEVROLET, year 2014 : 37 entries
CHEVROLET, year 2014 : 37 entries
CHEVROLET, year 2014 : 30 entries
CITROEN, year 2014 : 37 entries
CITROEN, year 2014 : 25 entries
FORD, year 2014 : 37 entries
FORD, year 2014 : 37 entries
FORD, year 2014 : 37 entries
FORD, year 2014 : 25 entries
HONDA, year 2014 : 30 entries
HYUNDAI, year 2014 : 38 entries
HYUNDAI, year 2014 : 37 entries
HYUNDAI, year 2014 : 37 entries
HYUNDAI, year 2014 : 37 entries
HYUNDAI, year 2014 : 37 entries
HYUNDAI, year 2014 : 37 entries
HYUNDAI, year 2014 : 34 entries
INFINITI, year 2014 : 38 entries
INFINITI, year 2014 : 24 entries
JEEP, year 2014 : 34 entries
KIA, year 2014 : 38 entries
KIA, year 2014 : 37 entries
KIA, year 2014 : 37 entries
KIA, year 2014 : 37 entries
KIA, year 2014 : 37 entries
KIA, year 2014 : 37 entries
KIA, year 2014 : 37 entries
KIA, year 2014 : 20 entries
LEXUS, year 2014 : 37 entries
LEXUS, year 2014 : 8 entries
MINI, year 2014 : 14 entries
MAZDA, year 2014 : 38 entries
MAZDA, year 2014 : 37 entries
MAZDA, year 2014 : 26 entries
MITSUBISHI, year 2014 : 37 entries
MITSUBISHI, year 2014 : 37 entries
MITSUBISHI, year 2014 : 28 entries
NISSAN, year 2014 : 37 entries
NISSAN, year 2014 : 37 entries
NISSAN, year 2014 : 37 entries
NISSAN, year 2014 : 37 entries
NISSAN, year 2014 : 37 entries
NISSAN, year 2014 : 37 entries
NISSAN, year 2014 : 37 entries
NISSAN, year 2014 : 37 entries
OPEL, year 2014 : 37 entries
OPEL, year 2014 : 37 entries
OPEL, year 2014 : 37 entries
OPEL, year 2014 : 37 entries
OPEL, year 2014 : 22 entries
PEUGEOT, year 2014 : 37 entries
PEUGEOT, year 2014 : 7 entries
PORSCHE, year 2014 : 38 entries
PORSCHE, year 2014 : 13 entries
RENAULT, year 2014 : 38 entries
RENAULT, year 2014 : 37 entries
RENAULT, year 2014 : 37 entries
RENAULT, year 2014 : 37 entries
RENAULT, year 2014 : 37 entries
RENAULT, year 2014 : 1 entries
SKODA, year 2014 : 38 entries
SKODA, year 2014 : 37 entries
SKODA, year 2014 : 37 entries
SKODA, year 2014 : 37 entries
SKODA, year 2014 : 37 entries
SKODA, year 2014 : 29 entries
SUBARU, year 2014 : 31 entries
SUZUKI, year 2014 : 33 entries
TOYOTA, year 2014 : 38 entries
TOYOTA, year 2014 : 37 entries
TOYOTA, year 2014 : 37 entries

TOYOTA, year 2014 : 37 entries
TOYOTA, year 2014 : 13 entries
VOLKSWAGEN, year 2014 : 38 entries
VOLKSWAGEN, year 2014 : 37 entries
VOLKSWAGEN, year 2014 : 37 entries
VOLKSWAGEN, year 2014 : 37 entries
VOLKSWAGEN, year 2014 : 37 entries
VOLKSWAGEN, year 2014 : 37 entries
VOLKSWAGEN, year 2014 : 34 entries
VOLVO, year 2014 : 38 entries
VOLVO, year 2014 : 29 entries
AUDI, year 2015 : 38 entries
AUDI, year 2015 : 37 entries
AUDI, year 2015 : 37 entries
AUDI, year 2015 : 37 entries
AUDI, year 2015 : 37 entries
AUDI, year 2015 : 4 entries
BMW, year 2015 : 38 entries
BMW, year 2015 : 37 entries
BMW, year 2015 : 37 entries
BMW, year 2015 : 37 entries
BMW, year 2015 : 37 entries
BMW, year 2015 : 20 entries
CHEVROLET, year 2015 : 38 entries
CHEVROLET, year 2015 : 21 entries
CITROEN, year 2015 : 23 entries
FORD, year 2015 : 37 entries
FORD, year 2015 : 37 entries
FORD, year 2015 : 37 entries
FORD, year 2015 : 14 entries
HONDA, year 2015 : 8 entries
HYUNDAI, year 2015 : 38 entries
HYUNDAI, year 2015 : 37 entries
HYUNDAI, year 2015 : 37 entries
HYUNDAI, year 2015 : 37 entries
HYUNDAI, year 2015 : 37 entries
HYUNDAI, year 2015 : 37 entries
HYUNDAI, year 2015 : 37 entries
HYUNDAI, year 2015 : 13 entries
INFINITI, year 2015 : 37 entries
INFINITI, year 2015 : 3 entries
JEEP, year 2015 : 4 entries
KIA, year 2015 : 38 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 37 entries
KIA, year 2015 : 4 entries
LEXUS, year 2015 : 37 entries
LEXUS, year 2015 : 29 entries
MINI, year 2015 : 9 entries
MAZDA, year 2015 : 37 entries
MAZDA, year 2015 : 18 entries
MITSUBISHI, year 2015 : 37 entries
MITSUBISHI, year 2015 : 10 entries
NISSAN, year 2015 : 38 entries
NISSAN, year 2015 : 37 entries
NISSAN, year 2015 : 37 entries
NISSAN, year 2015 : 37 entries
NISSAN, year 2015 : 37 entries
NISSAN, year 2015 : 37 entries
NISSAN, year 2015 : 23 entries
OPEL, year 2015 : 22 entries
PEUGEOT, year 2015 : 8 entries
PORSCHE, year 2015 : 38 entries
PORSCHE, year 2015 : 16 entries
RENAULT, year 2015 : 37 entries
RENAULT, year 2015 : 37 entries
RENAULT, year 2015 : 37 entries
SKODA, year 2015 : 38 entries
SKODA, year 2015 : 37 entries
SKODA, year 2015 : 37 entries
SKODA, year 2015 : 24 entries
SUBARU, year 2015 : 6 entries
SUZUKI, year 2015 : 4 entries
TOYOTA, year 2015 : 38 entries
TOYOTA, year 2015 : 37 entries
TOYOTA, year 2015 : 37 entries
TOYOTA, year 2015 : 37 entries
TOYOTA, year 2015 : 34 entries
VOLKSWAGEN, year 2015 : 37 entries
VOLKSWAGEN, year 2015 : 37 entries
VOLKSWAGEN, year 2015 : 37 entries
VOLKSWAGEN, year 2015 : 37 entries
VOLKSWAGEN, year 2015 : 37 entries
VOLKSWAGEN, year 2015 : 12 entries
VOLVO, year 2015 : 38 entries
VOLVO, year 2015 : 10 entries
AUDI, year 2016 : 38 entries
AUDI, year 2016 : 37 entries
AUDI, year 2016 : 37 entries
AUDI, year 2016 : 36 entries
BMW, year 2016 : 38 entries
BMW, year 2016 : 37 entries
BMW, year 2016 : 37 entries
BMW, year 2016 : 37 entries
BMW, year 2016 : 37 entries
BMW, year 2016 : 37 entries
BMW, year 2016 : 1 entries
CHEVROLET, year 2016 : 38 entries
CHEVROLET, year 2016 : 20 entries
CITROEN, year 2016 : 19 entries
FORD, year 2016 : 38 entries
FORD, year 2016 : 37 entries
FORD, year 2016 : 37 entries
FORD, year 2016 : 29 entries
HONDA, year 2016 : 8 entries
HYUNDAI, year 2016 : 38 entries
HYUNDAI, year 2016 : 37 entries
HYUNDAI, year 2016 : 37 entries
HYUNDAI, year 2016 : 37 entries
HYUNDAI, year 2016 : 37 entries
HYUNDAI, year 2016 : 37 entries
HYUNDAI, year 2016 : 37 entries
HYUNDAI, year 2016 : 28 entries
INFINITI, year 2016 : 30 entries
JEEP, year 2016 : 8 entries
KIA, year 2016 : 38 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 37 entries
KIA, year 2016 : 15 entries
LEXUS, year 2016 : 37 entries
LEXUS, year 2016 : 22 entries
MINI, year 2016 : 20 entries
MAZDA, year 2016 : 37 entries
MAZDA, year 2016 : 37 entries
MAZDA, year 2016 : 8 entries
MITSUBISHI, year 2016 : 37 entries
MITSUBISHI, year 2016 : 7 entries
NISSAN, year 2016 : 38 entries
NISSAN, year 2016 : 37 entries
NISSAN, year 2016 : 37 entries
NISSAN, year 2016 : 37 entries
NISSAN, year 2016 : 1 entries
OPEL, year 2016 : 1 entries
PEUGEOT, year 2016 : 16 entries
PORSCHE, year 2016 : 37 entries
PORSCHE, year 2016 : 12 entries
RENAULT, year 2016 : 38 entries
RENAULT, year 2016 : 37 entries
RENAULT, year 2016 : 37 entries
RENAULT, year 2016 : 27 entries
SKODA, year 2016 : 38 entries
SKODA, year 2016 : 37 entries
SKODA, year 2016 : 37 entries
SKODA, year 2016 : 37 entries
SKODA, year 2016 : 29 entries
SUBARU, year 2016 : 9 entries
SUZUKI, year 2016 : 10 entries
TOYOTA, year 2016 : 38 entries
TOYOTA, year 2016 : 37 entries
TOYOTA, year 2016 : 37 entries
TOYOTA, year 2016 : 37 entries
TOYOTA, year 2016 : 8 entries
VOLKSWAGEN, year 2016 : 38 entries
VOLKSWAGEN, year 2016 : 37 entries
VOLKSWAGEN, year 2016 : 37 entries
VOLKSWAGEN, year 2016 : 37 entries
VOLKSWAGEN, year 2016 : 37 entries
VOLKSWAGEN, year 2016 : 37 entries
VOLKSWAGEN, year 2016 : 6 entries
VOLVO, year 2016 : 31 entries
AUDI, year 2017 : 38 entries
AUDI, year 2017 : 37 entries
AUDI, year 2017 : 37 entries
BMW, year 2017 : 38 entries
BMW, year 2017 : 37 entries
BMW, year 2017 : 37 entries
BMW, year 2017 : 37 entries
BMW, year 2017 : 37 entries
BMW, year 2017 : 37 entries
BMW, year 2017 : 37 entries
BMW, year 2017 : 12 entries
CHEVROLET, year 2017 : 25 entries
CITROEN, year 2017 : 25 entries
FORD, year 2017 : 38 entries
FORD, year 2017 : 37 entries
FORD, year 2017 : 37 entries
FORD, year 2017 : 16 entries
HONDA, year 2017 : 11 entries
HYUNDAI, year 2017 : 38 entries
HYUNDAI, year 2017 : 37 entries
HYUNDAI, year 2017 : 37 entries
HYUNDAI, year 2017 : 37 entries
HYUNDAI, year 2017 : 37 entries
HYUNDAI, year 2017 : 37 entries
HYUNDAI, year 2017 : 37 entries
HYUNDAI, year 2017 : 37 entries
HYUNDAI, year 2017 : 7 entries
INFINITI, year 2017 : 33 entries
JEEP, year 2017 : 7 entries
KIA, year 2017 : 38 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 37 entries
KIA, year 2017 : 15 entries
LEXUS, year 2017 : 38 entries
LEXUS, year 2017 : 26 entries
MINI, year 2017 : 19 entries
MAZDA, year 2017 : 37 entries
MAZDA, year 2017 : 37 entries
MAZDA, year 2017 : 5 entries
MITSUBISHI, year 2017 : 38 entries
MITSUBISHI, year 2017 : 25 entries
NISSAN, year 2017 : 37 entries
NISSAN, year 2017 : 37 entries
NISSAN, year 2017 : 37 entries
NISSAN, year 2017 : 37 entries
NISSAN, year 2017 : 33 entries
PEUGEOT, year 2017 : 15 entries
PORSCHE, year 2017 : 37 entries
PORSCHE, year 2017 : 18 entries
RENAULT, year 2017 : 38 entries
RENAULT, year 2017 : 37 entries
RENAULT, year 2017 : 37 entries
RENAULT, year 2017 : 37 entries
RENAULT, year 2017 : 10 entries
SKODA, year 2017 : 38 entries
SKODA, year 2017 : 37 entries
SKODA, year 2017 : 37 entries
SKODA, year 2017 : 37 entries
SKODA, year 2017 : 36 entries
SUBARU, year 2017 : 10 entries
SUZUKI, year 2017 : 8 entries
TOYOTA, year 2017 : 38 entries
TOYOTA, year 2017 : 37 entries
TOYOTA, year 2017 : 37 entries
TOYOTA, year 2017 : 37 entries
TOYOTA, year 2017 : 8 entries
VOLKSWAGEN, year 2017 : 38 entries
VOLKSWAGEN, year 2017 : 37 entries
VOLKSWAGEN, year 2017 : 37 entries
VOLKSWAGEN, year 2017 : 37 entries
VOLKSWAGEN, year 2017 : 37 entries
VOLKSWAGEN, year 2017 : 37 entries
VOLKSWAGEN, year 2017 : 37 entries
VOLVO, year 2017 : 37 entries
VOLVO, year 2017 : 9 entries
AUDI, year 2018 : 37 entries
AUDI, year 2018 : 37 entries
AUDI, year 2018 : 6 entries
BMW, year 2018 : 37 entries
BMW, year 2018 : 37 entries
BMW, year 2018 : 37 entries
BMW, year 2018 : 37 entries
BMW, year 2018 : 37 entries
BMW, year 2018 : 37 entries
BMW, year 2018 : 37 entries
BMW, year 2018 : 26 entries
CHEVROLET, year 2018 : 21 entries
CITROEN, year 2018 : 17 entries

FORD, year 2018 : 37 entries
FORD, year 2018 : 37 entries
FORD, year 2018 : 3 entries
HONDA, year 2018 : 10 entries
HYUNDAI, year 2018 : 38 entries
HYUNDAI, year 2018 : 37 entries
HYUNDAI, year 2018 : 37 entries
HYUNDAI, year 2018 : 37 entries
HYUNDAI, year 2018 : 37 entries
HYUNDAI, year 2018 : 37 entries
HYUNDAI, year 2018 : 3 entries
INFINITI, year 2018 : 19 entries
JEEP, year 2018 : 18 entries
KIA, year 2018 : 38 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 37 entries
KIA, year 2018 : 25 entries
LEXUS, year 2018 : 37 entries
LEXUS, year 2018 : 19 entries
MINI, year 2018 : 27 entries
MAZDA, year 2018 : 37 entries
MAZDA, year 2018 : 13 entries
MITSUBISHI, year 2018 : 37 entries
MITSUBISHI, year 2018 : 37 entries
MITSUBISHI, year 2018 : 9 entries
NISSAN, year 2018 : 37 entries
NISSAN, year 2018 : 37 entries
NISSAN, year 2018 : 37 entries
NISSAN, year 2018 : 30 entries
PEUGEOT, year 2018 : 13 entries
PORSCHE, year 2018 : 37 entries
PORSCHE, year 2018 : 3 entries
RENAULT, year 2018 : 38 entries
RENAULT, year 2018 : 37 entries
RENAULT, year 2018 : 37 entries
RENAULT, year 2018 : 10 entries
SKODA, year 2018 : 38 entries
SKODA, year 2018 : 37 entries
SKODA, year 2018 : 37 entries
SKODA, year 2018 : 37 entries
SKODA, year 2018 : 36 entries
SUBARU, year 2018 : 7 entries
SUZUKI, year 2018 : 5 entries
TOYOTA, year 2018 : 38 entries
TOYOTA, year 2018 : 37 entries
TOYOTA, year 2018 : 37 entries
TOYOTA, year 2018 : 37 entries
TOYOTA, year 2018 : 28 entries
VOLKSWAGEN, year 2018 : 38 entries
VOLKSWAGEN, year 2018 : 37 entries
VOLKSWAGEN, year 2018 : 37 entries
VOLKSWAGEN, year 2018 : 37 entries
VOLKSWAGEN, year 2018 : 37 entries
VOLKSWAGEN, year 2018 : 17 entries
VOLVO, year 2018 : 20 entries
AUDI, year 2019 : 37 entries
AUDI, year 2019 : 37 entries
AUDI, year 2019 : 22 entries
BMW, year 2019 : 37 entries
BMW, year 2019 : 37 entries
BMW, year 2019 : 37 entries
BMW, year 2019 : 37 entries
BMW, year 2019 : 37 entries
BMW, year 2019 : 37 entries
BMW, year 2019 : 37 entries
BMW, year 2019 : 13 entries
CHEVROLET, year 2019 : 15 entries
CITROEN, year 2019 : 15 entries
FORD, year 2019 : 18 entries
HONDA, year 2019 : 2 entries
HYUNDAI, year 2019 : 38 entries
HYUNDAI, year 2019 : 37 entries
HYUNDAI, year 2019 : 37 entries
HYUNDAI, year 2019 : 37 entries
HYUNDAI, year 2019 : 37 entries
HYUNDAI, year 2019 : 20 entries
INFINITI, year 2019 : 37 entries
INFINITI, year 2019 : 37 entries
INFINITI, year 2019 : 18 entries
JEEP, year 2019 : 37 entries
JEEP, year 2019 : 2 entries
KIA, year 2019 : 38 entries
KIA, year 2019 : 37 entries
KIA, year 2019 : 37 entries
KIA, year 2019 : 37 entries
KIA, year 2019 : 37 entries
KIA, year 2019 : 37 entries
KIA, year 2019 : 37 entries
KIA, year 2019 : 37 entries
KIA, year 2019 : 2 entries
LEXUS, year 2019 : 37 entries
MINI, year 2019 : 20 entries
MAZDA, year 2019 : 37 entries
MAZDA, year 2019 : 23 entries
MITSUBISHI, year 2019 : 37 entries
MITSUBISHI, year 2019 : 34 entries
NISSAN, year 2019 : 38 entries
NISSAN, year 2019 : 37 entries
NISSAN, year 2019 : 33 entries
PEUGEOT, year 2019 : 9 entries
PORSCHE, year 2019 : 38 entries
PORSCHE, year 2019 : 7 entries
RENAULT, year 2019 : 37 entries
RENAULT, year 2019 : 37 entries
RENAULT, year 2019 : 13 entries
SKODA, year 2019 : 38 entries
SKODA, year 2019 : 37 entries
SKODA, year 2019 : 37 entries
SKODA, year 2019 : 37 entries
SKODA, year 2019 : 25 entries
SUBARU, year 2019 : 5 entries
SUZUKI, year 2019 : 9 entries
TOYOTA, year 2019 : 38 entries
TOYOTA, year 2019 : 37 entries
TOYOTA, year 2019 : 37 entries
TOYOTA, year 2019 : 23 entries
VOLKSWAGEN, year 2019 : 37 entries
VOLKSWAGEN, year 2019 : 37 entries
VOLKSWAGEN, year 2019 : 37 entries
VOLKSWAGEN, year 2019 : 19 entries
VOLVO, year 2019 : 36 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 37 entries
AUDI, year 2020 : 6 entries
BMW, year 2020 : 38 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 37 entries
BMW, year 2020 : 25 entries
CHEVROLET, year 2020 : 37 entries
CHEVROLET, year 2020 : 22 entries
CITROEN, year 2020 : 37 entries
CITROEN, year 2020 : 37 entries
CITROEN, year 2020 : 37 entries
CITROEN, year 2020 : 37 entries
CITROEN, year 2020 : 30 entries
FORD, year 2020 : 8 entries
HONDA, year 2020 : 31 entries
HYUNDAI, year 2020 : 38 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 37 entries
HYUNDAI, year 2020 : 36 entries
INFINITI, year 2020 : 15 entries
JEEP, year 2020 : 37 entries
JEEP, year 2020 : 37 entries
JEEP, year 2020 : 14 entries
KIA, year 2020 : 38 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 37 entries
KIA, year 2020 : 19 entries
LEXUS, year 2020 : 37 entries
LEXUS, year 2020 : 37 entries
LEXUS, year 2020 : 37 entries
LEXUS, year 2020 : 29 entries
MINI, year 2020 : 37 entries
MINI, year 2020 : 37 entries
MINI, year 2020 : 37 entries
MINI, year 2020 : 37 entries
MINI, year 2020 : 37 entries
MINI, year 2020 : 37 entries
MINI, year 2020 : 27 entries
MAZDA, year 2020 : 37 entries

MAZDA, year 2020 : 37 entries
MAZDA, year 2020 : 37 entries
MAZDA, year 2020 : 37 entries
MAZDA, year 2020 : 37 entries
MAZDA, year 2020 : 37 entries
MAZDA, year 2020 : 37 entries
MAZDA, year 2020 : 19 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 37 entries
MITSUBISHI, year 2020 : 3 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 37 entries
NISSAN, year 2020 : 31 entries
OPEL, year 2020 : 37 entries
OPEL, year 2020 : 37 entries
OPEL, year 2020 : 30 entries
PEUGEOT, year 2020 : 37 entries
PEUGEOT, year 2020 : 37 entries
PEUGEOT, year 2020 : 11 entries
PORSCHE, year 2020 : 37 entries
PORSCHE, year 2020 : 37 entries
PORSCHE, year 2020 : 20 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
RENAULT, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 37 entries
SKODA, year 2020 : 10 entries
SUBARU, year 2020 : 37 entries
SUBARU, year 2020 : 37 entries
SUBARU, year 2020 : 37 entries
SUBARU, year 2020 : 24 entries
SUZUKI, year 2020 : 37 entries
SUZUKI, year 2020 : 37 entries
SUZUKI, year 2020 : 37 entries
SUZUKI, year 2020 : 37 entries
SUZUKI, year 2020 : 37 entries
SUZUKI, year 2020 : 37 entries
SUZUKI, year 2020 : 37 entries
SUZUKI, year 2020 : 5 entries
TOYOTA, year 2020 : 37 entries
TOYOTA, year 2020 : 37 entries
TOYOTA, year 2020 : 10 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 37 entries
VOLKSWAGEN, year 2020 : 12 entries
VOLVO, year 2020 : 37 entries
VOLVO, year 2020 : 37 entries
VOLVO, year 2020 : 37 entries
VOLVO, year 2020 : 37 entries
VOLVO, year 2020 : 37 entries
VOLVO, year 2020 : 22 entries
AUDI, year 2021 : 22 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 37 entries
BMW, year 2021 : 1 entries
CHEVROLET, year 2021 : 1 entries
CITROEN, year 2021 : 19 entries
FORD, year 2021 : 1 entries
HYUNDAI, year 2021 : 37 entries
HYUNDAI, year 2021 : 5 entries
MINI, year 2021 : 37 entries
MINI, year 2021 : 14 entries
MAZDA, year 2021 : 22 entries
MITSUBISHI, year 2021 : 10 entries
NISSAN, year 2021 : 37 entries
NISSAN, year 2021 : 37 entries
NISSAN, year 2021 : 37 entries
NISSAN, year 2021 : 37 entries
NISSAN, year 2021 : 37 entries
NISSAN, year 2021 : 37 entries
NISSAN, year 2021 : 30 entries
OPEL, year 2021 : 2 entries
PEUGEOT, year 2021 : 33 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 37 entries
RENAULT, year 2021 : 14 entries
SKODA, year 2021 : 12 entries
SUZUKI, year 2021 : 37 entries
SUZUKI, year 2021 : 37 entries
SUZUKI, year 2021 : 37 entries
SUZUKI, year 2021 : 37 entries
SUZUKI, year 2021 : 37 entries
SUZUKI, year 2021 : 37 entries
SUZUKI, year 2021 : 17 entries
TOYOTA, year 2021 : 37 entries
TOYOTA, year 2021 : 37 entries
TOYOTA, year 2021 : 28 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries
VOLKSWAGEN, year 2021 : 37 entries

VOLKSWAGEN, year 2021 : 32 entries
VOLVO, year 2021 : 37 entries
VOLVO, year 2021 : 37 entries
VOLVO, year 2021 : 37 entries
VOLVO, year 2021 : 37 entries
VOLVO, year 2021 : 37 entries
VOLVO, year 2021 : 37 entries
VOLVO, year 2021 : 26 entries
Crawling done!!!

In [247]:
len(j)

60480

In [62]:
import json

def process_json_array(f):
    """
    This function processes the contents of a json file (please see save_to_json for details) to extract only the required
    attributes
    """
    with open(f, "r") as f:
        data = json.load(f)
    
    return data

In [63]:
from_json = process_json_array('data 2.json')

In [64]:
from_json[0]

{'availability': 'IN_STOCK',
 'category': 'cars',
 'color_hex': '007F00',
 'delivery_info': {},
 'description': 'Шевроле Камаро 1970 года Модификация Z28. На момент производства являлась самой спортивной версией модели. Это модель 1970 года, в Америке более известна как модель 70 с 1/2 года, так как из за забастовки на заводах General Motors эта модель производилась всего пол года в 1970 году. В 1971 году модель перетерпела внешние изменения, делая эту модель 1970 года более редкой. После 1970 года в Америке были введены новые правила по выбросам газов, вынуждая производителей жертвовать мощностью двигателей и их размерам в угоду законам.\n\nШевроле Камаро Z28 Special Performance Package комплектовалась с завода двигателем V8 LT-1 объёмом 350 кубических дюймов, то есть 5,7 литра. Этот двигатель в своей оригинальной форме должен был выдавать мощность около 360 л.с, и 520 Nm крутящего момента. После покупки машины в 2000 году на аукционе в Америке, машина приехала в Россию, и прошла глубокую реставрацию которая включала в себя полный разбор, чистку, и модернизацию двигателя, что позволило значительно повысить мощность и крутящий момент. В процессе жатой реконструкции так же была заменена коробка передач на специально созданную именно для этого двигателя в Америке 6 ступенчатую. Кузов машины был подвергнут тщательному осмотру и перекрашен заново в оригинальный цвет с применением технологии многослойной окраски. Салон был заново перетянут в кожу и алькантару так же оригинального цвета. Радио было заменено на современную аудиосистему с выходом USB. Диски были заменены на новые Mickey Thompson. Были установлены шины Continental и новые дисковые тормоза в замен барабанных. Суммарно, в машину было вложено более 100 тысяч Долларов не считая стоимости покупки.\n\nПоследние 20 лет машина находилась в частном отапливаемом гараже, и использовалась только летом. Не смотря на то что не каждый год машина использовалась, она проходила постоянные ТО в специализированном сервисе с заменой всех расходников. В последний год было заменено сцепление.\n\n Продается по причине окончательного переезда в другую страну.',
 'discount_options': {},
 'documents': {'owners_number': 2,
  'pts_original': True,
  'custom_cleared': True,
  'purchase_date': {'year': 2000, 'month': 5},
  'year': 1970,
  'vin': '124870N***********',
  'pts': 'ORIGINAL',
  'license_plate': '******|99'},
 'is_favorite': False,
 'old_category_id': 15,
 'owner_expenses': {'transport_tax': {'tax_by_year': 6975,
   'year': 2020,
   'rid': 213,
   'rate': 45,
   'horse_power': 155,
   'holding_period_month': 12,
   'boost': 1},
  'osago_insurance': [{'insurance_company': 'TINKOFF', 'price': 6309}]},
 'section': 'used',
 'seller_type': 'PRIVATE',
 'status': 'ACTIVE',
 'tags': ['big',
  'autoru_exclusive',
  'muscle',
  'available_for_checkup',
  'style',
  'low_mileage',
  'pts_original'],
 'additional_info': {'hidden': False,
  'is_on_moderation': False,
  'not_disturb': True,
  'update_date': '1609856644000',
  'creation_date': '1604955936000',
  'mobile_autoservices_url': 'https://m.auto.ru/autoservice/all_works/CHEVROLET/?geo_id=213',
  'hot_info': {'is_hot': False,
   'start_time': '2020-11-09T21:05:36Z',
   'end_time': '2020-11-09T21:05:36Z'},
  'fresh_date': '1604955936000',
  'counters_start_date': '1604955936000',
  'chat_only': False,
  'dealer_card_promo': 'DONT_SHOW',
  'review_summary': {},
  'price_stats': {'last_year_price_percentage_diff': -6},
  'booking': {},
  'days_in_stock': 64,
  'days_on_sale': 64},
 'counters': {},
 'grouping_info': None,
 'hash': 'bb39a2a5',
 'id': '1101533691',
 'price_info': {'price': 6950000,
  'currency': 'RUR',
  'EUR': 76946,
  'RUR': 6950000,
  'USD': 93582,
  'with_nds': False},
 'price_history': [{'EUR': 76946,
   'RUR': 6950000,
   'USD': 93582,
   'create_timestamp': 1604964664000}],
 'recall_info': {},
 'saleId': '1101533691-bb39a2a5',
 'salon': None,
 'seller': {'location': {'coord': {'latitude': 55.753216,
    'longitude': 37.622505},
   'geobase_id': '213',
   'region_info': {'id': '213',
    'name': 'Москва',
    'genitive': 'Москвы',
    'dative': 'Москве',
    'accusative': 'Москву',
    'prepositional': 'Москве',
    'preposition': 'в',
    'latitude': 55.753215,
    'longitude': 37.622504,
    'parent_ids': ['213', '1', '3', '225', '10001', '10000']},
   'timezone_info': {'abbr': 'MSK',
    'dst': False,
    'name': 'Europe/Moscow',
    'offset': 10800}},
  'name': 'Гавриил',
  'phones': [],
  'redirect_phones': True,
  'chats_enabled': True,
  'call_hours': {'call_hour_start': 14,
   'call_hour_end': 23,
   'call_minute_end': 0,
   'call_minute_start': 0}},
 'service_prices': [],
 'services': [],
 'state': {'mileage': 7613,
  'state_not_beaten': True,
  'image_urls': [{'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/1582741/c471fa80f4833f5eb0d2eb26d7ce2cc0/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/1582741/c471fa80f4833f5eb0d2eb26d7ce2cc0/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/1582741/c471fa80f4833f5eb0d2eb26d7ce2cc0/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/1582741/c471fa80f4833f5eb0d2eb26d7ce2cc0/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/1582741/c471fa80f4833f5eb0d2eb26d7ce2cc0/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/1582741/c471fa80f4833f5eb0d2eb26d7ce2cc0/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/1582741/c471fa80f4833f5eb0d2eb26d7ce2cc0/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDze18RjS9J1rX7fxd4Z1jU/EWrNfXdnp7Su1iHbLAq2W6MeBuK7fmFevan4I8TR+Co/GcV/p2o6WloJiljKzThW2MHCMgOMc49+nFeS/tVfDW8g0WGbwh4e0vT7nTJ3num0rTxBcXKODhmZAA/Az0+8jc9M+f+C/20fEXhXSL7w14rvbPxnpltBHLYLrEDTywzFVJVZM7hjJUhicFcDAyK469CNW7Ub/P/AIBCq16FvZpNGV8UPHPxB1LRxDd2msWyDY6lLVky2GDcqPQ/zorvfhF+0H4u+K/xB07TY4PDXhLRL1SZbK0uDtfbnBhglkcxueRhAobqeRmiqowjRjyOml/XoLnnU1mn959O+MI1OtQMVBY2EuTjk/vYa/O39p6wtrL4mXa29vFAGySIkC5P4UUV00/47N4/w0eq/st6fatBYSm2hMoYMHMY3ZB4OaKKK56vxMa2P//Z'},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/2049628/13b2e049cc48099f28cd31fac850296a/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/2049628/13b2e049cc48099f28cd31fac850296a/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/2049628/13b2e049cc48099f28cd31fac850296a/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/2049628/13b2e049cc48099f28cd31fac850296a/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/2049628/13b2e049cc48099f28cd31fac850296a/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/2049628/13b2e049cc48099f28cd31fac850296a/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/2049628/13b2e049cc48099f28cd31fac850296a/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDxm18T2/h3WFuNJ1DWLG5kt5bi7u9H85WA2h3MqsI2AOV6IF/2q9t8G6r4d8a6BJf6brscetO5t79bayABQovLo+Rv3gtuXBH/AAHNeV+PP2fvEWj6dqdzoGu6vquqyQ4VUiVYmYAA79zliCM8DP8ASvGG/wCFi+HY4Y/+Ef1e8ukA3vDav+7Yj5wNjszc47DvkV8/VVW16HK35+dr9V95vW9pCUowd10Pv7wR8D7Lxb4fgF14uuLi3OJfskW9VilZQGIwygk7epXJAFFcX+zppnjnwt4jQTyahqXhKSNnNxqMhMu4qCoVZAHUbmbg4xtGBg8FbxcbJTtc0gptao9mu4I/tDfu164+6K3DZW7WkeYIjjplBRRXFLdHd0K10fLXC/KBjgcUUUVqiD//2Q=='},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/2079642/d64899808cecc02ec3f8ae8a97ec8904/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/2079642/d64899808cecc02ec3f8ae8a97ec8904/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/2079642/d64899808cecc02ec3f8ae8a97ec8904/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/2079642/d64899808cecc02ec3f8ae8a97ec8904/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/2079642/d64899808cecc02ec3f8ae8a97ec8904/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/2079642/d64899808cecc02ec3f8ae8a97ec8904/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/2079642/d64899808cecc02ec3f8ae8a97ec8904/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD4Q1/4ueMfGOvSajd6jNczXSg5gVLYRhMgKpX7uPmIHqxPJJz+jP7LXj+x1PwBpmh2919s1HTIgZZVdXaZm5diAc5LZOea8Z8W/ssW1w0l94bmTQdQ2keVFEPs8oPVXT0PtXmfw5/Zgk1ibxRe6pNfaPr+mXcSpPpTNttEZSUnGBuwWUgDORsPPevExlBY6EYRly28r+n3HlYzA18TOL57JX87+vofp/pM9hqUsczQxC6TgTqQJPoSMEj2OaK/LLRP2pPiP4E8Q3mna1qo1LULOUwyvdncZdvGS6kbieu45znJzzRXzzjmuG/dJ3S7Sdj5qpCvSk4Sg9Ox96XSjyWOBnNct4MUD40XluABBdeFNSaeIfdmMckBjLjo20sxGem4460UV9VT/iI/QX8DPzk+PChPi/4vVQFVNSZVAHCgAAAUUUV6a2RzPc//2Q=='},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/1976162/30fd70e1c654d0ec1802adf480e2ce3a/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/1976162/30fd70e1c654d0ec1802adf480e2ce3a/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/1976162/30fd70e1c654d0ec1802adf480e2ce3a/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/1976162/30fd70e1c654d0ec1802adf480e2ce3a/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/1976162/30fd70e1c654d0ec1802adf480e2ce3a/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/1976162/30fd70e1c654d0ec1802adf480e2ce3a/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/1976162/30fd70e1c654d0ec1802adf480e2ce3a/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDlPEuk+O9I8Q6z8RLbULnwR4EgjW4bQIP3UyxRRhUPlwqUUZ+YqGyBkd68mvv2ktA1DT9X03UvE+qapaa0nl3aSXU8ccCLyiQxlH2KckEKRkcH1P6O6j4fsNYsp7O5iSe1mQpJGyZVlIwVI7g15Zc/sg/DC8umnfwtYqzHOEiCjP0HArhcU58z/rqZToRqWbPMP2WPGWk/Fnw9q+gXt1Pr+h6RDbwR28okhVTk7B987+EySc8gHqTkr6G8KfCnw98P7RrfQtMt9NhcgskEYQMfU460VMaMIqyX36nVTqVKMVCE2kvNnT7j5mMmrltzMAeRtP8ASiiugyJrofu/8+tFFFA2f//Z'},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/2101836/4430de68909a94b2056afcb8adda7179/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/2101836/4430de68909a94b2056afcb8adda7179/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/2101836/4430de68909a94b2056afcb8adda7179/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/2101836/4430de68909a94b2056afcb8adda7179/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/2101836/4430de68909a94b2056afcb8adda7179/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/2101836/4430de68909a94b2056afcb8adda7179/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/2101836/4430de68909a94b2056afcb8adda7179/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDxvx54Wn1NbfXtKj1iKGHTzLBsQkyyyDIQbPvOo54GB+ddt8Vvh78UPE9+fGGqXmn6rrl1pljYR2bRNZ3TwRpjzSkpCljj5tpxubIGOK8r/aE+KvjDwrcaPfafeT2Fws3nWr20rRGEAHBUrg8g9eCR164HKeBfEfxz1zSrCHTvFPig6VIwDi6unFpBE4IPzeZuKgc7RjPYZ65Wbhpa3S5jONXnvA6bxh4c8baJFJNPoepLL5TBXjtywjftk9OuPbiivpufVYptNhWCWVkWMKrSnEhwMZbrz65zRSjSp72udEm3uz5T0VF1b9osx3yi8QTTELcDzAMBscH0wPyr6ShJOoXSE5SO5KIvZV2KcAdhkniiisqn2fRG0OompfIzheACOlFFFaw2Mpbn/9k='}],
  'images_count': 11},
 'sub_category': 'cars',
 'vehicle_info': {'configuration': {'id': '20656932',
   'body_type': 'COUPE',
   'doors_count': 2,
   'auto_class': 'S',
   'human_name': 'Купе',
   'body_type_group': 'COUPE',
   'main_photo': {'sizes': {'orig': '//avatars.mds.yandex.net/get-verba/1030388/2a0000016090720f73213784826132d7a3ec/orig',
     'wizardv3mr': '//avatars.mds.yandex.net/get-verba/1030388/2a0000016090720f73213784826132d7a3ec/wizardv3mr',
     'cattouch': '//avatars.mds.yandex.net/get-verba/1030388/2a0000016090720f73213784826132d7a3ec/cattouch'}},
   'tags': ['muscle', 'big', 'style']},
  'complectation': {'id': '0'},
  'equipment': {'usb': True},
  'mark_info': {'code': 'CHEVROLET',
   'name': 'Chevrolet',
   'ru_name': 'Шевроле',
   'logo': {'name': 'mark-logo',
    'sizes': {'logo': '//avatars.mds.yandex.net/get-verba/787013/2a00000164d5630f090a35531e87bc5fc0e3/logo',
     'big-logo': '//avatars.mds.yandex.net/get-verba/787013/2a00000164d5630f090a35531e87bc5fc0e3/dealer_logo'}}},
  'model_info': {'code': 'CAMARO',
   'name': 'Camaro',
   'ru_name': 'Камаро',
   'morphology': {},
   'nameplate': {'code': '', 'name': '', 'semantic_url': ''}},
  'steering_wheel': 'LEFT',
  'super_gen': {'id': '20656892',
   'name': 'II',
   'ru_name': '2',
   'year_from': 1970,
   'year_to': 1981,
   'price_segment': 'MEDIUM'},
  'tech_param': {'id': '20656956',
   'displacement': 4093,
   'engine_type': 'GASOLINE',
   'gear_type': 'REAR_DRIVE',
   'transmission': 'MECHANICAL',
   'power': 155,
   'power_kvt': 115,
   'human_name': '4.1 MT (155 л.с.)',
   'acceleration': 12.2},
  'vendor': 'AMERICAN'},
 'lk_summary': '4.1\xa0MT (155\xa0л.с.), купе, задний, бензин',
 'multiposting': {}}

In [65]:
from_json[60000]

{'availability': 'ON_ORDER',
 'category': 'cars',
 'color_hex': '040001',
 'delivery_info': {},
 'description': 'Пакет "Зимние технологии"\nМногофункциональное рулевое колесо с кожаной отделкой и подогревом\n\nВнешнее оборудование\n----------------------------\nСветодиодные фары ближнего и дальнего света рефлекторного типа с отдельными дневными ходовыми огнями\nСветодиодные задние фонари\nЛегкосплавные колесные диски "Montana" 7J x 17", шины 215/65 R17\n\nИнтерьер\n----------------------------\nТканевая отделка "Quad Paper"\nСалонное зеркало заднего вида с ручным затемнением\n\nБезопасность\n----------------------------\nСистема контроля дистанции Front Assist с функцией экстренного торможения City Emergency Braking\nСистема распознавания усталости водителя\nСистема ЭРА ГЛОНАСС\nПередние подушки безопасности с функцией отключения пассажирской подушки\nБоковые шторки безопасности спереди и сзади и передние боковые подушки\nЭлектронная система стабилизации (ESP), антиблокировочная система (ABS) с функцией антипробуксовочной системы (ASR), электронная блокировка дифференциала (EDL) и стабилизация прицепа\n\nФункциональное оборудование\n----------------------------\nМногофункциональный цветной дисплей на приборной панели Premium\nТрёхзонная система климат-контроля Air Care Climatronic с фильтром пыльцы и сенсорным управлением спереди\nБеспроводной интерфейс для мобильного телефона Bluetooth\n8 динамиков\nЭлектромеханический стояночный тормоз с системой AutoHold\nДатчик дождя\nДва порта USB Type-C в центральной консоли\nАссистент движения на спуске (для полного привода 4Motion)\nВыбор режимов движения\nКруиз-контроль с ограничителем скорости\nЭлектромеханический усилитель рулевого управления, с переменной эффективностью в зависимости от скорости\nАудиосистема "Composition" с цветным дисплеем 6.5"\nСистема контроля давления в шинах\n\n* Стоимость данного автомобиля указана без учета предустановленного дополнительного оборудования.',
 'discount_price': {'price': 1898900, 'status': 'ACTIVE'},
 'discount_options': {'tradein': 40000, 'max_discount': 40000},
 'documents': {'pts_original': True,
  'custom_cleared': True,
  'year': 2021,
  'warranty': True,
  'warranty_expire': {'year': 2024, 'month': 1, 'day': 1},
  'pts': 'ORIGINAL'},
 'is_favorite': False,
 'old_category_id': 15,
 'owner_expenses': {'transport_tax': {'tax_by_year': 5250,
   'year': 2020,
   'rid': 213,
   'rate': 35,
   'horse_power': 150,
   'holding_period_month': 12,
   'boost': 1},
  'osago_insurance': [{'insurance_company': 'TINKOFF', 'price': 5521}]},
 'section': 'new',
 'seller_type': 'COMMERCIAL',
 'status': 'ACTIVE',
 'tags': ['new4new',
  'discount',
  'discount_options',
  'comfort',
  'dealer_discount',
  'dealer_quarantine_calls',
  'redemption'],
 'additional_info': {'hidden': False,
  'is_on_moderation': False,
  'exchange': True,
  'update_date': '1610467817000',
  'creation_date': '1610443418000',
  'mobile_autoservices_url': 'https://m.auto.ru/autoservice/all_works/VOLKSWAGEN/?geo_id=213',
  'hot_info': {'is_hot': False,
   'start_time': '2021-01-12T12:09:38Z',
   'end_time': '2021-01-12T12:09:38Z'},
  'redemption_available': True,
  'fresh_date': '1610443418000',
  'counters_start_date': '1610443418000',
  'chat_only': False,
  'dealer_card_promo': 'SLEEP_PROMO',
  'review_summary': {},
  'price_stats': {'last_year_price_percentage_diff': -9},
  'booking': {},
  'match_application_form': {'contexts': ['listing',
    'group_card',
    'gallery',
    'footer',
    'mixed-listing']},
  'days_in_stock': 1,
  'days_on_sale': 1},
 'counters': {},
 'grouping_info': None,
 'hash': '592be621',
 'id': '1102149066',
 'price_info': {'price': 1938900,
  'currency': 'RUR',
  'EUR': 21466,
  'RUR': 1938900,
  'USD': 26107,
  'with_nds': False},
 'price_history': [{'EUR': 21466,
   'RUR': 1938900,
   'USD': 26107,
   'create_timestamp': 1610453377000}],
 'recall_info': {},
 'saleId': '1102149066-592be621',
 'salon': {'actual_stock': True,
  'client_id': '8538',
  'code': 'volkswagen_centr_losiny_ostrov_moskva',
  'dealer_id': '20136850',
  'logo_url': '//avatars.mds.yandex.net/get-verba/937147/2a00000169d836a9c098e13c996113d09deb/dealer_logo',
  'offer_counters': {'cars_all': 187, 'trucks_all': 1},
  'name': 'Volkswagen Центр Лосиный Остров',
  'phones': [{'phone': '+7 495 598-58-58'}],
  'place': {'address': 'Московская обл., Ярославское шоссе, владение 2В, строение 1 (95 км МКАД)',
   'coord': {'latitude': 55.881573, 'longitude': 37.732727},
   'geobase_id': '10740',
   'region_info': {'id': '10740',
    'name': 'Мытищи',
    'genitive': 'Мытищ',
    'dative': 'Мытищам',
    'accusative': 'Мытищи',
    'prepositional': 'Мытищах',
    'preposition': 'в',
    'latitude': 55.910503,
    'longitude': 37.73633,
    'parent_ids': ['10740', '98596', '1', '3', '225', '10001', '10000']}},
  'registration_date': '2013-08-26T20:00:00Z',
  'salon_id': '8495',
  'is_official': True},
 'seller': {'location': {'address': 'МО, г.Мытищи, Ярославское шоссе, владение 2В, строение 1',
   'coord': {'latitude': 55.881485, 'longitude': 37.732735},
   'geobase_id': '213',
   'region_info': {'id': '213',
    'name': 'Москва',
    'genitive': 'Москвы',
    'dative': 'Москве',
    'accusative': 'Москву',
    'prepositional': 'Москве',
    'preposition': 'в',
    'latitude': 55.753215,
    'longitude': 37.622504,
    'parent_ids': ['213', '1', '3', '225', '10001', '10000']},
   'timezone_info': {'abbr': 'MSK',
    'dst': False,
    'name': 'Europe/Moscow',
    'offset': 10800}},
  'name': 'Volkswagen Центр Лосиный Остров',
  'phones': [],
  'redirect_phones': False,
  'chats_enabled': False,
  'call_hours': {'call_hour_start': 9,
   'call_hour_end': 21,
   'call_minute_end': 0,
   'call_minute_start': 0}},
 'service_prices': [],
 'services': [],
 'state': {'state_not_beaten': True,
  'image_urls': [{'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/3939611/0e95abf54c1f75d26a680a94ca01e26e/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/3939611/0e95abf54c1f75d26a680a94ca01e26e/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/3939611/0e95abf54c1f75d26a680a94ca01e26e/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/3939611/0e95abf54c1f75d26a680a94ca01e26e/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/3939611/0e95abf54c1f75d26a680a94ca01e26e/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/3939611/0e95abf54c1f75d26a680a94ca01e26e/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/3939611/0e95abf54c1f75d26a680a94ca01e26e/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9OfFXi/Q/A2iz6x4h1az0XS4BmS7vplijHGcZJ5PHAHJ7V8wal/wU4+EFjcXUcUWu3scLhUmihtkWcFgoaNZJ1YjnPKg46iuu/bJ/Zs8SftF6F4Tg8M+J4PD93omotdyQ3sfmW90jJtOV2uN69VJVgCSeuK+RND/4JS/ERtXaPXPGOjS6EN5gjt9RuTLbOzqWeNfs6IDtDLjGMOeo4oEfpR4J8ZaV8QvCmmeItEuRd6XqEImhlHp0IPuCCCPUGiuO/Zy+DZ+Anwl0nwW2qtrclk80j3zRmPzDJKz/AHcnGAwHBwSCcDOAUDPTKKKKACiiigD/2Q=='},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/2080053/1e685ff28a147fbf6b6afa002e9570e9/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/2080053/1e685ff28a147fbf6b6afa002e9570e9/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/2080053/1e685ff28a147fbf6b6afa002e9570e9/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/2080053/1e685ff28a147fbf6b6afa002e9570e9/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/2080053/1e685ff28a147fbf6b6afa002e9570e9/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/2080053/1e685ff28a147fbf6b6afa002e9570e9/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/2080053/1e685ff28a147fbf6b6afa002e9570e9/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9QPEOvWXhbQdR1nUpvs+n6fbyXVxLgnZGilmOByeAeBXzH4X/AOClHwk8Ua5YaaIdf0wXbhRe6hawx28XbLsJiQPwz3AxXt/x4+Gc3xj+EfiXwZb6kdIn1a3EKXoDHyiHVwflIP8ADjg9/wAK/OyT/gll8YZPE00x8XeEG0bEsFvBc3FzcvbwMxKqoe2IyBgdegPrQI/UfTNTtNZ061v7C5ivLK6iWaC4hYMkiMMqykdQQQc0V5V+yf8ACPxD8C/gR4d8F+KNZt9d1jTvOEl1aFzCFeV3RELgMQqsByB9MUUDPXqKKKACiiigD//Z'},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/2160984/f3c6e6e36d7961808168e30b6d570e89/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/2160984/f3c6e6e36d7961808168e30b6d570e89/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/2160984/f3c6e6e36d7961808168e30b6d570e89/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/2160984/f3c6e6e36d7961808168e30b6d570e89/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/2160984/f3c6e6e36d7961808168e30b6d570e89/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/2160984/f3c6e6e36d7961808168e30b6d570e89/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/2160984/f3c6e6e36d7961808168e30b6d570e89/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9Bvjx8etA/Z/8Kw6zrcN1fS3U3kWthZKGmmYDLEZIAVRyT246kivBPAf/AAU/+Gfi3X4NM1LTdV8N+YxR7m72SRxMDj5thJCnrnFes/tTfstaH+1L4V03SdWvn0q506dp7a9S2ScruA3LtbjBKpyCD8tfEXiX/gkx8QtKVU8JeNtAvJsyI+oam09tI0LD/VeUscygBsHhhn0pCP018N+KdG8Y6XHqWharZazp8n3bmwnWaM+25SRnnpRXzt+wv+yjr37LnhXX7bxJrdjquqavJb7o9KDi1iSFXCsN6qxkbzDubuFQYGKKYz6dooooAKKKKAP/2Q=='},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/3926749/1437cc6c880c34a3a844ae285ca6bf4b/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/3926749/1437cc6c880c34a3a844ae285ca6bf4b/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/3926749/1437cc6c880c34a3a844ae285ca6bf4b/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/3926749/1437cc6c880c34a3a844ae285ca6bf4b/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/3926749/1437cc6c880c34a3a844ae285ca6bf4b/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/3926749/1437cc6c880c34a3a844ae285ca6bf4b/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/3926749/1437cc6c880c34a3a844ae285ca6bf4b/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD7l+Pf7XXgD9nbULLTPEc13fazdwm5TTNLWJ51hyQJGEkiAAlWA5ydpwODXDeB/wDgo/8AB7xnq8Gn3F3qHhqSZVZZtaW3SLJJABaOZ9pyD1x69KoftUfsDWP7R3jyHxba+Kp/Deptax2l1/o5n8yOPfsCHeAgJcFgVYHaDwea+eLj/gkf4nit5Yz4507XN0LoEvJLm2iEpB2SbFDgFT29zQI/SzSNd03xBai50vULXUrY8ia0mWVD+Kkiivlf9iT9jTxL+zPq+v6v4n8WQ69eajbrax29kSYEQFDubdGrFwVPOcYY8Z5ooGfW1FFFABRRRQB//9k='},
   {'sizes': {'small': '//avatars.mds.yandex.net/get-autoru-vos/1907070/58c6caba5d325d651cf69d5df7ad6824/small',
     'thumb_m': '//avatars.mds.yandex.net/get-autoru-vos/1907070/58c6caba5d325d651cf69d5df7ad6824/thumb_m',
     '320x240': '//avatars.mds.yandex.net/get-autoru-vos/1907070/58c6caba5d325d651cf69d5df7ad6824/320x240',
     '456x342': '//avatars.mds.yandex.net/get-autoru-vos/1907070/58c6caba5d325d651cf69d5df7ad6824/456x342',
     '456x342n': '//avatars.mds.yandex.net/get-autoru-vos/1907070/58c6caba5d325d651cf69d5df7ad6824/456x342n',
     '1200x900': '//avatars.mds.yandex.net/get-autoru-vos/1907070/58c6caba5d325d651cf69d5df7ad6824/1200x900',
     '1200x900n': '//avatars.mds.yandex.net/get-autoru-vos/1907070/58c6caba5d325d651cf69d5df7ad6824/1200x900n'},
    'preview': 'data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/wAARCAASABgDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD9Bvjz8e/Dn7Png9dd1/zrmSeXyLPT7Xb51zJjJxuIAVRyzE8D1JAPydF/wVp0FtalsZfAU8ccUoRpV1hHcqcHIRYsng5xn8a9e/bm/ZU1j9pnwz4ck8N6lZ2PiHQJpzBFqYzaTRTqiyhwFY7sRrg9OWyORj46+Hv/AASK+IF5dz2/jHxLoek6W2wRyabcTXcqKM70EToqENwcsxwR0pagfo/8GPj54L+Pmhzal4Q1Nrs2wj+2WdxC0NxaM4JVZEYd9rcjKnacE4ornf2Z/wBlnwr+y54cv9L8N3V9fSag0bXVzfMm5im/aFVFUKoMj8YPXrwKKYHstFFFABRRRQB//9k='}],
  'mileage': 0,
  'images_count': 7},
 'sub_category': 'cars',
 'vehicle_info': {'configuration': {'id': '22679065',
   'body_type': 'ALLROAD_5_DOORS',
   'doors_count': 5,
   'auto_class': 'J',
   'human_name': 'Внедорожник 5 дв.',
   'trunk_volume_min': 615,
   'trunk_volume_max': 1655,
   'body_type_group': 'ALLROAD_5_DOORS',
   'main_photo': {'sizes': {'orig': '//avatars.mds.yandex.net/get-verba/1030388/2a0000017641c483687436059c4170ad9154/orig',
     'wizardv3mr': '//avatars.mds.yandex.net/get-verba/1030388/2a0000017641c483687436059c4170ad9154/wizardv3mr',
     'cattouch': '//avatars.mds.yandex.net/get-verba/1030388/2a0000017641c483687436059c4170ad9154/cattouch'}}},
  'complectation': {'id': '22701321',
   'name': 'Respect Plus',
   'available_options': ['cruise-control',
    'multi-wheel',
    'heated-wash-system',
    'airbag-passenger',
    'navigation',
    'roof-rails',
    'bas',
    'lock',
    'electro-mirrors',
    'mirrors-heat',
    'glonass',
    'drowsy-driver-alert-system',
    'automatic-lighting-control',
    'passenger-seat-updown',
    'collision-prevention-assist',
    'computer',
    'seat-transformation',
    'android-auto',
    'fabric-seats',
    'airbag-side',
    'abs',
    'wheel-leather',
    'auto-mirrors',
    'asr',
    'esp',
    'usb',
    'audiopreparation',
    'audiosystem-tv',
    'front-centre-armrest',
    'apple-carplay',
    'rear-camera',
    'servo',
    'drl',
    'electro-window-back',
    'reduce-spare-wheel',
    'multizone-climate-control',
    '17-inch-wheels',
    'park-assist-f',
    'wheel-heat',
    'led-lights',
    'park-assist-r',
    'airbag-driver',
    'isofix',
    'drive-mode-sys',
    'electro-window-front',
    'light-sensor',
    'hcc',
    'airbag-curtain',
    'leather-gear-stick',
    'rain-sensor',
    'tyre-pressure',
    'audiosystem-cd',
    'front-seats-heat',
    'bluetooth',
    'wheel-configuration2',
    'wheel-configuration1',
    'immo',
    'windscreen-heat',
    '12v-socket',
    'third-rear-headrest'],
   'vendor_colors': [{'body_color_id': 22701028,
     'mark_color_id': 21391463,
     'name_ru': 'Белый Pure',
     'hex_codes': ['F2F3F2'],
     'color_type': 'NOT_METALLIC',
     'stock_color': {'hex_code': 'FAFBFB', 'name_ru': 'белый'},
     'photos': [{'name': '34-front',
       'sizes': {'orig': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/orig',
        'wizardv3mr': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/wizardv3mr',
        'wizardv3': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/wizardv3',
        'cattouch': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/cattouch',
        'small': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/small',
        '320x240': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/320x240',
        '1200x900': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/1200x900',
        '1200x900n': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/1200x900n',
        'thumb_m': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/thumb_m',
        'full': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/full',
        '832x624': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/832x624',
        '456x342': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/456x342',
        '120x90': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/120x90',
        '92x69': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/92x69',
        'islandoff': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/islandoff',
        'thumb_s': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/thumb_s',
        'thumb_s_2x': '//avatars.mds.yandex.net/get-verba/216201/2a0000017675f33acf47440e7392fb39106c/thumb_s_2x'}},
      {'name': '34-back',

In [66]:
from_json[0]['vehicle_info']['configuration']['human_name']

'Купе'

In [67]:
from_json[60000]['vehicle_info']['configuration']['human_name']

'Внедорожник 5 дв.'

In [68]:
# Took the idea from https://www.kaggle.com/sokolovaleks/sf-dst-10-p1-parsing-almira-andrey-sokolov
# and changed it to fit my requirements

# dictionary of the columns we need ( +/- what we have in test.csv)
dict_columns = {'bodyType':0, 'brand':0, 'color_hex':0, 'complectation_dict':0, 'equipment_dict':0, 
                'fuelType':0, 'modelDate':0, 'model_info':0, 'model_name':0, 'name':0, 'numberOfDoors':0, 'productionDate':0, 
                'vehicleConfiguration':0, 'vehicleTransmission':0, 'vendor':0,    
                'engineDisplacement':0, 'enginePower':0, 'description':0, 
                'mileage':0, 'Привод':0, 'Руль':0, 
                'Состояние':0, 'Владельцы':0, 'ПТС':0, 'Таможня':0, 
                'Владение':0, 'price':0}

def from_elem_to_dict(d_elem, dict_cols, result):
    """
    This function will be used to map json fields to dict_columns while looping through the list of JSONs. 
    """
    d_dict = dict_columns.copy()
    
    try: d_dict['bodyType'] = d_elem['vehicle_info']['configuration']['human_name']
    except: d_dict['bodyType'] = None

    try: d_dict['brand'] = d_elem['vehicle_info']['mark_info']['code']
    except: d_dict['brand'] = None

    try: d_dict['color_hex'] = d_elem['color_hex']
    except: d_dict['color_hex'] = None  
        
    try: d_dict['complectation_dict'] = d_elem['vehicle_info']['complectation']
    except: d_dict['complectation_dict'] = None     
        
    try: d_dict['equipment_dict'] = d_elem['vehicle_info']['equipment']
    except: d_dict['equipment_dict'] = None           

    try: d_dict['fuelType'] = d_elem['lk_summary'].split()[-1]
    except: d_dict['fuelType'] = None

    try: d_dict['modelDate'] = d_elem['vehicle_info']['super_gen']['year_from']
    except: d_dict['modelDate'] = None
        
    try: d_dict['model_info'] = d_elem['vehicle_info']['model_info']
    except: d_dict['model_info'] = None        
        
    try: d_dict['model_name'] = d_elem['vehicle_info']['model_info']['ru_name']
    except: d_dict['model_name'] = None             

    try: d_dict['name'] =  d_elem['vehicle_info']['tech_param']['human_name']
    except: d_dict['name'] = None

    try: d_dict['numberOfDoors'] = d_elem['vehicle_info']['configuration']['doors_count']
    except: d_dict['numberOfDoors'] = None

    try: d_dict['productionDate'] = d_elem['documents']['year']
    except: d_dict['productionDate'] = None

    try: d_dict['vehicleTransmission'] = d_elem['vehicle_info']['tech_param']['transmission']
    except: d_dict['vehicleTransmission'] = None
        
    try: d_dict['vendor'] = d_elem['vehicle_info']['vendor']
    except: d_dict['vendor'] = None    

    try: d_dict['engineDisplacement'] = d_elem['vehicle_info']['tech_param']['human_name'].split()[0]
    except: d_dict['engineDisplacement'] = None

    try: d_dict['vehicleConfiguration'] = d_elem['vehicle_info']['configuration']
    except: d_dict['vehicleConfiguration'] = None

    try: d_dict['enginePower'] = d_elem['vehicle_info']['tech_param']['power']
    except: d_dict['enginePower'] = None

    try: d_dict['description'] = d_elem['description']
    except: d_dict['description'] = None

    try: d_dict['mileage'] = d_elem['state']['mileage']
    except: d_dict['mileage'] = None

    try: d_dict['Привод'] = d_elem['lk_summary'].split(', ')[-2]
    except: d_dict['Привод'] = None

    try: d_dict['Руль'] = d_elem['vehicle_info']['steering_wheel']
    except: d_dict['Руль'] = None

    try: d_dict['Состояние'] = d_elem['section']
    except: d_dict['Состояние'] = None

    try: d_dict['Владельцы'] = d_elem['documents']['owners_number']
    except: d_dict['Владельцы'] = None

    try: d_dict['ПТС'] = d_elem['documents']['pts']
    except: d_dict['ПТС'] = None

    try: d_dict['Таможня'] = d_elem['documents']['custom_cleared']
    except: d_dict['Таможня'] = None

    try: d_dict['Владение'] =  d_elem['documents']['purchase_date']
    except: d_dict['Владение'] = None

    try: d_dict['price'] = d_elem['price_info']['RUR']
    except: d_dict['price'] = None

    result.append(d_dict)

In [69]:
result = []

for i in from_json:
    from_elem_to_dict(d_elem=i, dict_cols=dict_columns, result=result)

In [70]:
df_result = pd.DataFrame(result)

In [71]:
df_result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60480 entries, 0 to 60479
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   bodyType              60478 non-null  object
 1   brand                 60480 non-null  object
 2   color_hex             60480 non-null  object
 3   complectation_dict    60480 non-null  object
 4   equipment_dict        60480 non-null  object
 5   fuelType              60480 non-null  object
 6   modelDate             60478 non-null  float64
 7   model_info            60480 non-null  object
 8   model_name            60480 non-null  object
 9   name                  60478 non-null  object
 10  numberOfDoors         60478 non-null  float64
 11  productionDate        60480 non-null  int64
 12  vehicleConfiguration  60478 non-null  object
 13  vehicleTransmission   60478 non-null  object
 14  vendor                60480 non-null  object
 15  engineDisplacement    60478 non-null  object
 16  enginePower           60478 non-null  float64
 17  description           57948 non-null  object
 18  mileage               60480 non-null  int64
 19  Привод                60478 non-null  object
 20  Руль                  60480 non-null  object
 21  Состояние             60480 non-null  object
 22  Владельцы             46546 non-null  float64
 23  ПТС                   60146 non-null  object
 24  Таможня               60480 non-null  bool
 25  Владение              14320 non-null  object
 26  price                 60218 non-null  float64
dtypes: bool(1), float64(5), int64(2), object(19)
memory usage: 12.1+ MB

In [72]:
df_result.to_csv('own_train_set.csv')

In [60]:
df_result.to_excel('own_train_set.xlsx')